/**
 * @file    Fzc_Cfg.h
 * @brief   FZC configuration — all FZC-specific ID definitions
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef FZC_CFG_H
#define FZC_CFG_H

/* ====================================================================
 * RTE Signal IDs (offset 16 from BSW well-known)
 * ==================================================================== */

#define FZC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    16u
#define FZC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    17u
#define FZC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    18u
#define FZC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    19u
#define FZC_SIG_BCM_HEARTBEAT_ECU_ID    20u
#define FZC_SIG_BATTERY_STATUS_BATTERY_STATUS    21u
#define FZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V    22u
#define FZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER    23u
#define FZC_SIG_BATTERY_STATUS_E_2_E_CRC_8    24u
#define FZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID    25u
#define FZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD    26u
#define FZC_SIG_BODY_CONTROL_CMD_HAZARD_CMD    27u
#define FZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD    28u
#define FZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD    29u
#define FZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD    30u
#define FZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    31u
#define FZC_SIG_BRAKE_COMMAND_BRAKE_MODE    32u
#define FZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    33u
#define FZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8    34u
#define FZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    35u
#define FZC_SIG_BRAKE_COMMAND_VEHICLE_STATE    36u
#define FZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE    37u
#define FZC_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    38u
#define FZC_SIG_BRAKE_FAULT_E_2_E_CRC_8    39u
#define FZC_SIG_BRAKE_FAULT_E_2_E_DATA_ID    40u
#define FZC_SIG_BRAKE_FAULT_FAULT_TYPE    41u
#define FZC_SIG_BRAKE_FAULT_MEASURED_BRAKE    42u
#define FZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    43u
#define FZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    44u
#define FZC_SIG_BRAKE_STATUS_BRAKE_MODE    45u
#define FZC_SIG_BRAKE_STATUS_BRAKE_POSITION    46u
#define FZC_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    47u
#define FZC_SIG_BRAKE_STATUS_E_2_E_CRC_8    48u
#define FZC_SIG_BRAKE_STATUS_E_2_E_DATA_ID    49u
#define FZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    50u
#define FZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    51u
#define FZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    52u
#define FZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    53u
#define FZC_SIG_CVC_HEARTBEAT_ECU_ID    54u
#define FZC_SIG_CVC_HEARTBEAT_FAULT_STATUS    55u
#define FZC_SIG_CVC_HEARTBEAT_OPERATING_MODE    56u
#define FZC_SIG_DTC_BROADCAST_DTC_NUMBER    57u
#define FZC_SIG_DTC_BROADCAST_DTC_STATUS    58u
#define FZC_SIG_DTC_BROADCAST_ECU_SOURCE    59u
#define FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0    60u
#define FZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1    61u
#define FZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    62u
#define FZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK    63u
#define FZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK    64u
#define FZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK    65u
#define FZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK    66u
#define FZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK    67u
#define FZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    68u
#define FZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    69u
#define FZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    70u
#define FZC_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    71u
#define FZC_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    72u
#define FZC_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    73u
#define FZC_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    74u
#define FZC_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    75u
#define FZC_SIG_FZC_HEARTBEAT_ECU_ID    76u
#define FZC_SIG_FZC_HEARTBEAT_FAULT_STATUS    77u
#define FZC_SIG_FZC_HEARTBEAT_OPERATING_MODE    78u
#define FZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    79u
#define FZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    80u
#define FZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    81u
#define FZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    82u
#define FZC_SIG_ICU_HEARTBEAT_ECU_ID    83u
#define FZC_SIG_INDICATOR_STATE_BLINK_STATE    84u
#define FZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE    85u
#define FZC_SIG_INDICATOR_STATE_LEFT_INDICATOR    86u
#define FZC_SIG_INDICATOR_STATE_RIGHT_INDICATOR    87u
#define FZC_SIG_LIDAR_DISTANCE_DISTANCE_CM    88u
#define FZC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER    89u
#define FZC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8    90u
#define FZC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID    91u
#define FZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE    92u
#define FZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS    93u
#define FZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH    94u
#define FZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON    95u
#define FZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON    96u
#define FZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL    97u
#define FZC_SIG_LIGHT_STATUS_HEADLIGHT_ON    98u
#define FZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON    99u
#define FZC_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   100u
#define FZC_SIG_MOTOR_CURRENT_CURRENT_M_A   101u
#define FZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   102u
#define FZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8   103u
#define FZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   104u
#define FZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE   105u
#define FZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   106u
#define FZC_SIG_MOTOR_CURRENT_TORQUE_ECHO   107u
#define FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   108u
#define FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   109u
#define FZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   110u
#define FZC_SIG_MOTOR_CUTOFF_REQ_REASON   111u
#define FZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   112u
#define FZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   113u
#define FZC_SIG_MOTOR_STATUS_E_2_E_CRC_8   114u
#define FZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID   115u
#define FZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION   116u
#define FZC_SIG_MOTOR_STATUS_MOTOR_ENABLE   117u
#define FZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   118u
#define FZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   119u
#define FZC_SIG_MOTOR_STATUS_TORQUE_ECHO   120u
#define FZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   121u
#define FZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   122u
#define FZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   123u
#define FZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   124u
#define FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   125u
#define FZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   126u
#define FZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER   127u
#define FZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8   128u
#define FZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID   129u
#define FZC_SIG_RZC_HEARTBEAT_ECU_ID   130u
#define FZC_SIG_RZC_HEARTBEAT_FAULT_STATUS   131u
#define FZC_SIG_RZC_HEARTBEAT_OPERATING_MODE   132u
#define FZC_SIG_SC_STATUS_ECU_HEALTH   133u
#define FZC_SIG_SC_STATUS_FAULT_REASON   134u
#define FZC_SIG_SC_STATUS_RELAY_STATE   135u
#define FZC_SIG_SC_STATUS_SC_ALIVE_COUNTER   136u
#define FZC_SIG_SC_STATUS_SC_CRC_8   137u
#define FZC_SIG_SC_STATUS_SC_FAULT_FLAGS   138u
#define FZC_SIG_SC_STATUS_SC_MODE   139u
#define FZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER   140u
#define FZC_SIG_STEER_COMMAND_E_2_E_CRC_8   141u
#define FZC_SIG_STEER_COMMAND_E_2_E_DATA_ID   142u
#define FZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD   143u
#define FZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT   144u
#define FZC_SIG_STEER_COMMAND_VEHICLE_STATE   145u
#define FZC_SIG_STEERING_STATUS_ACTUAL_ANGLE   146u
#define FZC_SIG_STEERING_STATUS_COMMANDED_ANGLE   147u
#define FZC_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER   148u
#define FZC_SIG_STEERING_STATUS_E_2_E_CRC_8   149u
#define FZC_SIG_STEERING_STATUS_E_2_E_DATA_ID   150u
#define FZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A   151u
#define FZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS   152u
#define FZC_SIG_STEERING_STATUS_STEER_MODE   153u
#define FZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER   154u
#define FZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER   155u
#define FZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8   156u
#define FZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID   157u
#define FZC_SIG_TCU_HEARTBEAT_ECU_ID   158u
#define FZC_SIG_TORQUE_REQUEST_DIRECTION   159u
#define FZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER   160u
#define FZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8   161u
#define FZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID   162u
#define FZC_SIG_TORQUE_REQUEST_PEDAL_FAULT   163u
#define FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1   164u
#define FZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2   165u
#define FZC_SIG_TORQUE_REQUEST_TORQUE_REQUEST   166u
#define FZC_SIG_UDS_FUNC_REQUEST_UDS_DATA   167u
#define FZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   168u
#define FZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   169u
#define FZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   170u
#define FZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   171u
#define FZC_SIG_UDS_RESP_CVC_UDS_DATA   172u
#define FZC_SIG_UDS_RESP_FZC_UDS_DATA   173u
#define FZC_SIG_UDS_RESP_RZC_UDS_DATA   174u
#define FZC_SIG_UDS_RESP_TCU_UDS_DATA   175u
#define FZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER   176u
#define FZC_SIG_VEHICLE_STATE_E_2_E_CRC_8   177u
#define FZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID   178u
#define FZC_SIG_VEHICLE_STATE_FAULT_MASK   179u
#define FZC_SIG_VEHICLE_STATE_SPEED_LIMIT   180u
#define FZC_SIG_VEHICLE_STATE_TORQUE_LIMIT   181u
#define FZC_SIG_VEHICLE_STATE_VEHICLE_STATE   182u
#define FZC_SIG_COUNT   183u

/* ====================================================================
 * Com TX PDU IDs
 * ==================================================================== */

#define FZC_COM_TX_FZC_HEARTBEAT     0u   /* CAN 0x011 */
#define FZC_COM_TX_STEERING_STATUS     1u   /* CAN 0x200 */
#define FZC_COM_TX_BRAKE_STATUS     2u   /* CAN 0x201 */
#define FZC_COM_TX_BRAKE_FAULT     3u   /* CAN 0x210 */
#define FZC_COM_TX_MOTOR_CUTOFF_REQ     4u   /* CAN 0x211 */
#define FZC_COM_TX_LIDAR_DISTANCE     5u   /* CAN 0x220 */
#define FZC_COM_TX_DTC_BROADCAST     6u   /* CAN 0x500 */
#define FZC_COM_TX_UDS_RESP_FZC     7u   /* CAN 0x7E9 */

/* ====================================================================
 * Com RX PDU IDs
 * ==================================================================== */

#define FZC_COM_RX_ESTOP_BROADCAST     0u   /* CAN 0x001 */
#define FZC_COM_RX_CVC_HEARTBEAT     1u   /* CAN 0x010 */
#define FZC_COM_RX_RZC_HEARTBEAT     2u   /* CAN 0x012 */
#define FZC_COM_RX_SC_STATUS     3u   /* CAN 0x013 */
#define FZC_COM_RX_ICU_HEARTBEAT     4u   /* CAN 0x014 */
#define FZC_COM_RX_TCU_HEARTBEAT     5u   /* CAN 0x015 */
#define FZC_COM_RX_BCM_HEARTBEAT     6u   /* CAN 0x016 */
#define FZC_COM_RX_VEHICLE_STATE     7u   /* CAN 0x100 */
#define FZC_COM_RX_TORQUE_REQUEST     8u   /* CAN 0x101 */
#define FZC_COM_RX_STEER_COMMAND     9u   /* CAN 0x102 */
#define FZC_COM_RX_BRAKE_COMMAND    10u   /* CAN 0x103 */
#define FZC_COM_RX_MOTOR_STATUS    11u   /* CAN 0x300 */
#define FZC_COM_RX_MOTOR_CURRENT    12u   /* CAN 0x301 */
#define FZC_COM_RX_MOTOR_TEMPERATURE    13u   /* CAN 0x302 */
#define FZC_COM_RX_BATTERY_STATUS    14u   /* CAN 0x303 */
#define FZC_COM_RX_BODY_CONTROL_CMD    15u   /* CAN 0x350 */
#define FZC_COM_RX_LIGHT_STATUS    16u   /* CAN 0x400 */
#define FZC_COM_RX_INDICATOR_STATE    17u   /* CAN 0x401 */
#define FZC_COM_RX_DOOR_LOCK_STATUS    18u   /* CAN 0x402 */
#define FZC_COM_RX_DTC_BROADCAST    19u   /* CAN 0x500 */
#define FZC_COM_RX_UDS_RESP_TCU    20u   /* CAN 0x644 */
#define FZC_COM_RX_UDS_FUNC_REQUEST    21u   /* CAN 0x7DF */
#define FZC_COM_RX_UDS_PHYS_REQ_CVC    22u   /* CAN 0x7E0 */
#define FZC_COM_RX_UDS_PHYS_REQ_FZC    23u   /* CAN 0x7E1 */
#define FZC_COM_RX_UDS_PHYS_REQ_RZC    24u   /* CAN 0x7E2 */
#define FZC_COM_RX_UDS_PHYS_REQ_TCU    25u   /* CAN 0x7E3 */
#define FZC_COM_RX_UDS_RESP_CVC    26u   /* CAN 0x7E8 */
#define FZC_COM_RX_UDS_RESP_RZC    27u   /* CAN 0x7EA */

/* ====================================================================
 * Com Signal IDs (index into Com signal config table)
 * Use these instead of hardcoded numbers in Com_SendSignal/Com_ReceiveSignal
 * ==================================================================== */

#define FZC_COM_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID     0u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER     1u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_FZC_HEARTBEAT_E_2_E_CRC_8     2u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_FZC_HEARTBEAT_ECU_ID     3u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_FZC_HEARTBEAT_OPERATING_MODE     4u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_FZC_HEARTBEAT_FAULT_STATUS     5u   /* TX FZC_Heartbeat */
#define FZC_COM_SIG_STEERING_STATUS_E_2_E_DATA_ID     6u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER     7u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_E_2_E_CRC_8     8u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_ACTUAL_ANGLE     9u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_COMMANDED_ANGLE    10u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_STEER_FAULT_STATUS    11u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_STEER_MODE    12u   /* TX Steering_Status */
#define FZC_COM_SIG_STEERING_STATUS_SERVO_CURRENT_M_A    13u   /* TX Steering_Status */
#define FZC_COM_SIG_BRAKE_STATUS_E_2_E_DATA_ID    14u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    15u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_E_2_E_CRC_8    16u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_BRAKE_POSITION    17u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    18u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    19u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    20u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_STATUS_BRAKE_MODE    21u   /* TX Brake_Status */
#define FZC_COM_SIG_BRAKE_FAULT_E_2_E_DATA_ID    22u   /* TX Brake_Fault */
#define FZC_COM_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    23u   /* TX Brake_Fault */
#define FZC_COM_SIG_BRAKE_FAULT_E_2_E_CRC_8    24u   /* TX Brake_Fault */
#define FZC_COM_SIG_BRAKE_FAULT_FAULT_TYPE    25u   /* TX Brake_Fault */
#define FZC_COM_SIG_BRAKE_FAULT_COMMANDED_BRAKE    26u   /* TX Brake_Fault */
#define FZC_COM_SIG_BRAKE_FAULT_MEASURED_BRAKE    27u   /* TX Brake_Fault */
#define FZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID    28u   /* TX Motor_Cutoff_Req */
#define FZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER    29u   /* TX Motor_Cutoff_Req */
#define FZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8    30u   /* TX Motor_Cutoff_Req */
#define FZC_COM_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE    31u   /* TX Motor_Cutoff_Req */
#define FZC_COM_SIG_MOTOR_CUTOFF_REQ_REASON    32u   /* TX Motor_Cutoff_Req */
#define FZC_COM_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID    33u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER    34u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_E_2_E_CRC_8    35u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_DISTANCE_CM    36u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH    37u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE    38u   /* TX Lidar_Distance */
#define FZC_COM_SIG_LIDAR_DISTANCE_SENSOR_STATUS    39u   /* TX Lidar_Distance */
#define FZC_COM_SIG_DTC_BROADCAST_DTC_NUMBER    40u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_DTC_BROADCAST_DTC_STATUS    41u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_DTC_BROADCAST_ECU_SOURCE    42u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    43u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_0    44u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_1    45u   /* TX DTC_Broadcast */
#define FZC_COM_SIG_UDS_RESP_FZC_UDS_DATA    46u   /* TX UDS_Resp_FZC */
#define FZC_COM_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    47u   /* RX EStop_Broadcast */
#define FZC_COM_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    48u   /* RX EStop_Broadcast */
#define FZC_COM_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    49u   /* RX EStop_Broadcast */
#define FZC_COM_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    50u   /* RX EStop_Broadcast */
#define FZC_COM_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    51u   /* RX EStop_Broadcast */
#define FZC_COM_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    52u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    53u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    54u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_CVC_HEARTBEAT_ECU_ID    55u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_CVC_HEARTBEAT_OPERATING_MODE    56u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_CVC_HEARTBEAT_FAULT_STATUS    57u   /* RX CVC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID    58u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    59u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_E_2_E_CRC_8    60u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_ECU_ID    61u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_OPERATING_MODE    62u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_RZC_HEARTBEAT_FAULT_STATUS    63u   /* RX RZC_Heartbeat */
#define FZC_COM_SIG_SC_STATUS_SC_ALIVE_COUNTER    64u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_SC_CRC_8    65u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_SC_MODE    66u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_SC_FAULT_FLAGS    67u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_ECU_HEALTH    68u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_FAULT_REASON    69u   /* RX SC_Status */
#define FZC_COM_SIG_SC_STATUS_RELAY_STATE    70u   /* RX SC_Status */
#define FZC_COM_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    71u   /* RX ICU_Heartbeat */
#define FZC_COM_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    72u   /* RX ICU_Heartbeat */
#define FZC_COM_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    73u   /* RX ICU_Heartbeat */
#define FZC_COM_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    74u   /* RX ICU_Heartbeat */
#define FZC_COM_SIG_ICU_HEARTBEAT_ECU_ID    75u   /* RX ICU_Heartbeat */
#define FZC_COM_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID    76u   /* RX TCU_Heartbeat */
#define FZC_COM_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER    77u   /* RX TCU_Heartbeat */
#define FZC_COM_SIG_TCU_HEARTBEAT_E_2_E_CRC_8    78u   /* RX TCU_Heartbeat */
#define FZC_COM_SIG_TCU_HEARTBEAT_ALIVE_COUNTER    79u   /* RX TCU_Heartbeat */
#define FZC_COM_SIG_TCU_HEARTBEAT_ECU_ID    80u   /* RX TCU_Heartbeat */
#define FZC_COM_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    81u   /* RX BCM_Heartbeat */
#define FZC_COM_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    82u   /* RX BCM_Heartbeat */
#define FZC_COM_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    83u   /* RX BCM_Heartbeat */
#define FZC_COM_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    84u   /* RX BCM_Heartbeat */
#define FZC_COM_SIG_BCM_HEARTBEAT_ECU_ID    85u   /* RX BCM_Heartbeat */
#define FZC_COM_SIG_VEHICLE_STATE_E_2_E_DATA_ID    86u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER    87u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_E_2_E_CRC_8    88u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_VEHICLE_STATE    89u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_FAULT_MASK    90u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_TORQUE_LIMIT    91u   /* RX Vehicle_State */
#define FZC_COM_SIG_VEHICLE_STATE_SPEED_LIMIT    92u   /* RX Vehicle_State */
#define FZC_COM_SIG_TORQUE_REQUEST_E_2_E_DATA_ID    93u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER    94u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_E_2_E_CRC_8    95u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_TORQUE_REQUEST    96u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_DIRECTION    97u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_1    98u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_2    99u   /* RX Torque_Request */
#define FZC_COM_SIG_TORQUE_REQUEST_PEDAL_FAULT   100u   /* RX Torque_Request */
#define FZC_COM_SIG_STEER_COMMAND_E_2_E_DATA_ID   101u   /* RX Steer_Command */
#define FZC_COM_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER   102u   /* RX Steer_Command */
#define FZC_COM_SIG_STEER_COMMAND_E_2_E_CRC_8   103u   /* RX Steer_Command */
#define FZC_COM_SIG_STEER_COMMAND_STEER_ANGLE_CMD   104u   /* RX Steer_Command */
#define FZC_COM_SIG_STEER_COMMAND_STEER_RATE_LIMIT   105u   /* RX Steer_Command */
#define FZC_COM_SIG_STEER_COMMAND_VEHICLE_STATE   106u   /* RX Steer_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_E_2_E_DATA_ID   107u   /* RX Brake_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER   108u   /* RX Brake_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_E_2_E_CRC_8   109u   /* RX Brake_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD   110u   /* RX Brake_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_BRAKE_MODE   111u   /* RX Brake_Command */
#define FZC_COM_SIG_BRAKE_COMMAND_VEHICLE_STATE   112u   /* RX Brake_Command */
#define FZC_COM_SIG_MOTOR_STATUS_E_2_E_DATA_ID   113u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   114u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_E_2_E_CRC_8   115u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_TORQUE_ECHO   116u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   117u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_MOTOR_DIRECTION   118u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_MOTOR_ENABLE   119u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   120u   /* RX Motor_Status */
#define FZC_COM_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   121u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   122u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_E_2_E_CRC_8   123u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_CURRENT_M_A   124u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   125u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_MOTOR_ENABLE   126u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   127u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_CURRENT_TORQUE_ECHO   128u   /* RX Motor_Current */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   129u   /* RX Motor_Temperature */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   130u   /* RX Motor_Temperature */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   131u   /* RX Motor_Temperature */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   132u   /* RX Motor_Temperature */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   133u   /* RX Motor_Temperature */
#define FZC_COM_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   134u   /* RX Motor_Temperature */
#define FZC_COM_SIG_BATTERY_STATUS_E_2_E_DATA_ID   135u   /* RX Battery_Status */
#define FZC_COM_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER   136u   /* RX Battery_Status */
#define FZC_COM_SIG_BATTERY_STATUS_E_2_E_CRC_8   137u   /* RX Battery_Status */
#define FZC_COM_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V   138u   /* RX Battery_Status */
#define FZC_COM_SIG_BATTERY_STATUS_BATTERY_STATUS   139u   /* RX Battery_Status */
#define FZC_COM_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD   140u   /* RX Body_Control_Cmd */
#define FZC_COM_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD   141u   /* RX Body_Control_Cmd */
#define FZC_COM_SIG_BODY_CONTROL_CMD_HAZARD_CMD   142u   /* RX Body_Control_Cmd */
#define FZC_COM_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD   143u   /* RX Body_Control_Cmd */
#define FZC_COM_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD   144u   /* RX Body_Control_Cmd */
#define FZC_COM_SIG_LIGHT_STATUS_HEADLIGHT_ON   145u   /* RX Light_Status */
#define FZC_COM_SIG_LIGHT_STATUS_TAIL_LIGHT_ON   146u   /* RX Light_Status */
#define FZC_COM_SIG_LIGHT_STATUS_FOG_LIGHT_ON   147u   /* RX Light_Status */
#define FZC_COM_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON   148u   /* RX Light_Status */
#define FZC_COM_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL   149u   /* RX Light_Status */
#define FZC_COM_SIG_INDICATOR_STATE_LEFT_INDICATOR   150u   /* RX Indicator_State */
#define FZC_COM_SIG_INDICATOR_STATE_RIGHT_INDICATOR   151u   /* RX Indicator_State */
#define FZC_COM_SIG_INDICATOR_STATE_HAZARD_ACTIVE   152u   /* RX Indicator_State */
#define FZC_COM_SIG_INDICATOR_STATE_BLINK_STATE   153u   /* RX Indicator_State */
#define FZC_COM_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK   154u   /* RX Door_Lock_Status */
#define FZC_COM_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK   155u   /* RX Door_Lock_Status */
#define FZC_COM_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK   156u   /* RX Door_Lock_Status */
#define FZC_COM_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK   157u   /* RX Door_Lock_Status */
#define FZC_COM_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK   158u   /* RX Door_Lock_Status */
#define FZC_COM_SIG_UDS_RESP_TCU_UDS_DATA   159u   /* RX UDS_Resp_TCU */
#define FZC_COM_SIG_UDS_FUNC_REQUEST_UDS_DATA   160u   /* RX UDS_Func_Request */
#define FZC_COM_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   161u   /* RX UDS_Phys_Req_CVC */
#define FZC_COM_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   162u   /* RX UDS_Phys_Req_FZC */
#define FZC_COM_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   163u   /* RX UDS_Phys_Req_RZC */
#define FZC_COM_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   164u   /* RX UDS_Phys_Req_TCU */
#define FZC_COM_SIG_UDS_RESP_CVC_UDS_DATA   165u   /* RX UDS_Resp_CVC */
#define FZC_COM_SIG_UDS_RESP_RZC_UDS_DATA   166u   /* RX UDS_Resp_RZC */
#define FZC_COM_SIG_COUNT   167u

/* ====================================================================
 * DTC Event IDs (Dem_EventIdType)
 * ==================================================================== */

#define FZC_DTC_STEER_PLAUSIBILITY     0u
#define FZC_DTC_STEER_RANGE     1u
#define FZC_DTC_STEER_RATE     2u
#define FZC_DTC_STEER_TIMEOUT     3u
#define FZC_DTC_STEER_SPI_FAIL     4u
#define FZC_DTC_BRAKE_FAULT     5u
#define FZC_DTC_BRAKE_TIMEOUT     6u
#define FZC_DTC_BRAKE_PWM_FAIL     7u
#define FZC_DTC_LIDAR_TIMEOUT     8u
#define FZC_DTC_LIDAR_CHECKSUM     9u
#define FZC_DTC_LIDAR_STUCK    10u
#define FZC_DTC_LIDAR_SIGNAL_LOW    11u
#define FZC_DTC_CAN_BUS_OFF    12u
#define FZC_DTC_SELF_TEST_FAIL    13u
#define FZC_DTC_WATCHDOG_FAIL    14u
#define FZC_DTC_BRAKE_OSCILLATION    15u

/* ====================================================================
 * E2E Data IDs
 * ==================================================================== */

#define FZC_E2E_HEARTBEAT_DATA_ID  0x03u
#define FZC_E2E_STEER_STATUS_DATA_ID  0x20u
#define FZC_E2E_BRAKE_STATUS_DATA_ID  0x21u
#define FZC_E2E_LIDAR_DATA_ID  0x22u
#define FZC_E2E_ESTOP_DATA_ID  0x01u
#define FZC_E2E_VEHSTATE_DATA_ID  0x10u
#define FZC_E2E_STEER_CMD_DATA_ID  0x12u
#define FZC_E2E_BRAKE_CMD_DATA_ID  0x13u

/* ====================================================================
 * Enums
 * ==================================================================== */

#define FZC_STATE_INIT     0u
#define FZC_STATE_RUN     1u
#define FZC_STATE_DEGRADED     2u
#define FZC_STATE_LIMP     3u
#define FZC_STATE_SAFE_STOP     4u
#define FZC_STATE_SHUTDOWN     5u
#define FZC_STATE_COUNT     6u

/* ====================================================================
 * Thresholds
 * ==================================================================== */

#define FZC_RTE_PERIOD_MS    10u
#define FZC_COMM_TIMEOUT   100u
#define FZC_STEER_MAX_ANGLE   450u
#define FZC_STEER_DEADBAND     5u
#define FZC_BRAKE_MAX_PRESSURE  1000u
#define FZC_LIDAR_MAX_RANGE  4000u
#define FZC_LIDAR_MIN_RANGE    50u

/* ====================================================================
 * Application-specific constants (hand-authored, not generated)
 * ==================================================================== */
#if __has_include("Fzc_App.h")
#include "Fzc_App.h"
#endif

#endif /* FZC_CFG_H */
