/**
 * @file    Cvc_Cfg.h
 * @brief   CVC configuration — all CVC-specific ID definitions
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef CVC_CFG_H
#define CVC_CFG_H

/* ====================================================================
 * RTE Signal IDs (offset 16 from BSW well-known)
 * ==================================================================== */

#define CVC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    16u
#define CVC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    17u
#define CVC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    18u
#define CVC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    19u
#define CVC_SIG_BCM_HEARTBEAT_ECU_ID    20u
#define CVC_SIG_BATTERY_STATUS_BATTERY_STATUS    21u
#define CVC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V    22u
#define CVC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER    23u
#define CVC_SIG_BATTERY_STATUS_E_2_E_CRC_8    24u
#define CVC_SIG_BATTERY_STATUS_E_2_E_DATA_ID    25u
#define CVC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD    26u
#define CVC_SIG_BODY_CONTROL_CMD_HAZARD_CMD    27u
#define CVC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD    28u
#define CVC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD    29u
#define CVC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD    30u
#define CVC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    31u
#define CVC_SIG_BRAKE_COMMAND_BRAKE_MODE    32u
#define CVC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    33u
#define CVC_SIG_BRAKE_COMMAND_E_2_E_CRC_8    34u
#define CVC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    35u
#define CVC_SIG_BRAKE_COMMAND_VEHICLE_STATE    36u
#define CVC_SIG_BRAKE_FAULT_COMMANDED_BRAKE    37u
#define CVC_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    38u
#define CVC_SIG_BRAKE_FAULT_E_2_E_CRC_8    39u
#define CVC_SIG_BRAKE_FAULT_E_2_E_DATA_ID    40u
#define CVC_SIG_BRAKE_FAULT_FAULT_TYPE    41u
#define CVC_SIG_BRAKE_FAULT_MEASURED_BRAKE    42u
#define CVC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    43u
#define CVC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    44u
#define CVC_SIG_BRAKE_STATUS_BRAKE_MODE    45u
#define CVC_SIG_BRAKE_STATUS_BRAKE_POSITION    46u
#define CVC_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    47u
#define CVC_SIG_BRAKE_STATUS_E_2_E_CRC_8    48u
#define CVC_SIG_BRAKE_STATUS_E_2_E_DATA_ID    49u
#define CVC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    50u
#define CVC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    51u
#define CVC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    52u
#define CVC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    53u
#define CVC_SIG_CVC_HEARTBEAT_ECU_ID    54u
#define CVC_SIG_CVC_HEARTBEAT_FAULT_STATUS    55u
#define CVC_SIG_CVC_HEARTBEAT_OPERATING_MODE    56u
#define CVC_SIG_DTC_BROADCAST_DTC_NUMBER    57u
#define CVC_SIG_DTC_BROADCAST_DTC_STATUS    58u
#define CVC_SIG_DTC_BROADCAST_ECU_SOURCE    59u
#define CVC_SIG_DTC_BROADCAST_FREEZE_FRAME_0    60u
#define CVC_SIG_DTC_BROADCAST_FREEZE_FRAME_1    61u
#define CVC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    62u
#define CVC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK    63u
#define CVC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK    64u
#define CVC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK    65u
#define CVC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK    66u
#define CVC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK    67u
#define CVC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    68u
#define CVC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    69u
#define CVC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    70u
#define CVC_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    71u
#define CVC_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    72u
#define CVC_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    73u
#define CVC_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    74u
#define CVC_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    75u
#define CVC_SIG_FZC_HEARTBEAT_ECU_ID    76u
#define CVC_SIG_FZC_HEARTBEAT_FAULT_STATUS    77u
#define CVC_SIG_FZC_HEARTBEAT_OPERATING_MODE    78u
#define CVC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    79u
#define CVC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    80u
#define CVC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    81u
#define CVC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    82u
#define CVC_SIG_ICU_HEARTBEAT_ECU_ID    83u
#define CVC_SIG_INDICATOR_STATE_BLINK_STATE    84u
#define CVC_SIG_INDICATOR_STATE_HAZARD_ACTIVE    85u
#define CVC_SIG_INDICATOR_STATE_LEFT_INDICATOR    86u
#define CVC_SIG_INDICATOR_STATE_RIGHT_INDICATOR    87u
#define CVC_SIG_LIDAR_DISTANCE_DISTANCE_CM    88u
#define CVC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER    89u
#define CVC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8    90u
#define CVC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID    91u
#define CVC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE    92u
#define CVC_SIG_LIDAR_DISTANCE_SENSOR_STATUS    93u
#define CVC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH    94u
#define CVC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON    95u
#define CVC_SIG_LIGHT_STATUS_FOG_LIGHT_ON    96u
#define CVC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL    97u
#define CVC_SIG_LIGHT_STATUS_HEADLIGHT_ON    98u
#define CVC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON    99u
#define CVC_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   100u
#define CVC_SIG_MOTOR_CURRENT_CURRENT_M_A   101u
#define CVC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   102u
#define CVC_SIG_MOTOR_CURRENT_E_2_E_CRC_8   103u
#define CVC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   104u
#define CVC_SIG_MOTOR_CURRENT_MOTOR_ENABLE   105u
#define CVC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   106u
#define CVC_SIG_MOTOR_CURRENT_TORQUE_ECHO   107u
#define CVC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   108u
#define CVC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   109u
#define CVC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   110u
#define CVC_SIG_MOTOR_CUTOFF_REQ_REASON   111u
#define CVC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   112u
#define CVC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   113u
#define CVC_SIG_MOTOR_STATUS_E_2_E_CRC_8   114u
#define CVC_SIG_MOTOR_STATUS_E_2_E_DATA_ID   115u
#define CVC_SIG_MOTOR_STATUS_MOTOR_DIRECTION   116u
#define CVC_SIG_MOTOR_STATUS_MOTOR_ENABLE   117u
#define CVC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   118u
#define CVC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   119u
#define CVC_SIG_MOTOR_STATUS_TORQUE_ECHO   120u
#define CVC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   121u
#define CVC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   122u
#define CVC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   123u
#define CVC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   124u
#define CVC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   125u
#define CVC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   126u
#define CVC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER   127u
#define CVC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8   128u
#define CVC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID   129u
#define CVC_SIG_RZC_HEARTBEAT_ECU_ID   130u
#define CVC_SIG_RZC_HEARTBEAT_FAULT_STATUS   131u
#define CVC_SIG_RZC_HEARTBEAT_OPERATING_MODE   132u
#define CVC_SIG_SC_STATUS_ECU_HEALTH   133u
#define CVC_SIG_SC_STATUS_FAULT_REASON   134u
#define CVC_SIG_SC_STATUS_RELAY_STATE   135u
#define CVC_SIG_SC_STATUS_SC_ALIVE_COUNTER   136u
#define CVC_SIG_SC_STATUS_SC_CRC_8   137u
#define CVC_SIG_SC_STATUS_SC_FAULT_FLAGS   138u
#define CVC_SIG_SC_STATUS_SC_MODE   139u
#define CVC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER   140u
#define CVC_SIG_STEER_COMMAND_E_2_E_CRC_8   141u
#define CVC_SIG_STEER_COMMAND_E_2_E_DATA_ID   142u
#define CVC_SIG_STEER_COMMAND_STEER_ANGLE_CMD   143u
#define CVC_SIG_STEER_COMMAND_STEER_RATE_LIMIT   144u
#define CVC_SIG_STEER_COMMAND_VEHICLE_STATE   145u
#define CVC_SIG_STEERING_STATUS_ACTUAL_ANGLE   146u
#define CVC_SIG_STEERING_STATUS_COMMANDED_ANGLE   147u
#define CVC_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER   148u
#define CVC_SIG_STEERING_STATUS_E_2_E_CRC_8   149u
#define CVC_SIG_STEERING_STATUS_E_2_E_DATA_ID   150u
#define CVC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A   151u
#define CVC_SIG_STEERING_STATUS_STEER_FAULT_STATUS   152u
#define CVC_SIG_STEERING_STATUS_STEER_MODE   153u
#define CVC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER   154u
#define CVC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER   155u
#define CVC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8   156u
#define CVC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID   157u
#define CVC_SIG_TCU_HEARTBEAT_ECU_ID   158u
#define CVC_SIG_TORQUE_REQUEST_DIRECTION   159u
#define CVC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER   160u
#define CVC_SIG_TORQUE_REQUEST_E_2_E_CRC_8   161u
#define CVC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID   162u
#define CVC_SIG_TORQUE_REQUEST_PEDAL_FAULT   163u
#define CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1   164u
#define CVC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2   165u
#define CVC_SIG_TORQUE_REQUEST_TORQUE_REQUEST   166u
#define CVC_SIG_UDS_FUNC_REQUEST_UDS_DATA   167u
#define CVC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   168u
#define CVC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   169u
#define CVC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   170u
#define CVC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   171u
#define CVC_SIG_UDS_RESP_CVC_UDS_DATA   172u
#define CVC_SIG_UDS_RESP_FZC_UDS_DATA   173u
#define CVC_SIG_UDS_RESP_RZC_UDS_DATA   174u
#define CVC_SIG_UDS_RESP_TCU_UDS_DATA   175u
#define CVC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER   176u
#define CVC_SIG_VEHICLE_STATE_E_2_E_CRC_8   177u
#define CVC_SIG_VEHICLE_STATE_E_2_E_DATA_ID   178u
#define CVC_SIG_VEHICLE_STATE_FAULT_MASK   179u
#define CVC_SIG_VEHICLE_STATE_SPEED_LIMIT   180u
#define CVC_SIG_VEHICLE_STATE_TORQUE_LIMIT   181u
#define CVC_SIG_VEHICLE_STATE_VEHICLE_STATE   182u
#define CVC_SIG_COUNT   183u

/* ====================================================================
 * Com TX PDU IDs
 * ==================================================================== */

#define CVC_COM_TX_ESTOP_BROADCAST     0u   /* CAN 0x001 */
#define CVC_COM_TX_CVC_HEARTBEAT     1u   /* CAN 0x010 */
#define CVC_COM_TX_VEHICLE_STATE     2u   /* CAN 0x100 */
#define CVC_COM_TX_TORQUE_REQUEST     3u   /* CAN 0x101 */
#define CVC_COM_TX_STEER_COMMAND     4u   /* CAN 0x102 */
#define CVC_COM_TX_BRAKE_COMMAND     5u   /* CAN 0x103 */
#define CVC_COM_TX_BODY_CONTROL_CMD     6u   /* CAN 0x350 */
#define CVC_COM_TX_DTC_BROADCAST     7u   /* CAN 0x500 */
#define CVC_COM_TX_UDS_RESP_CVC     8u   /* CAN 0x7E8 */

/* ====================================================================
 * Com RX PDU IDs
 * ==================================================================== */

#define CVC_COM_RX_FZC_HEARTBEAT     0u   /* CAN 0x011 */
#define CVC_COM_RX_RZC_HEARTBEAT     1u   /* CAN 0x012 */
#define CVC_COM_RX_SC_STATUS     2u   /* CAN 0x013 */
#define CVC_COM_RX_ICU_HEARTBEAT     3u   /* CAN 0x014 */
#define CVC_COM_RX_TCU_HEARTBEAT     4u   /* CAN 0x015 */
#define CVC_COM_RX_BCM_HEARTBEAT     5u   /* CAN 0x016 */
#define CVC_COM_RX_STEERING_STATUS     6u   /* CAN 0x200 */
#define CVC_COM_RX_BRAKE_STATUS     7u   /* CAN 0x201 */
#define CVC_COM_RX_BRAKE_FAULT     8u   /* CAN 0x210 */
#define CVC_COM_RX_MOTOR_CUTOFF_REQ     9u   /* CAN 0x211 */
#define CVC_COM_RX_LIDAR_DISTANCE    10u   /* CAN 0x220 */
#define CVC_COM_RX_MOTOR_STATUS    11u   /* CAN 0x300 */
#define CVC_COM_RX_MOTOR_CURRENT    12u   /* CAN 0x301 */
#define CVC_COM_RX_MOTOR_TEMPERATURE    13u   /* CAN 0x302 */
#define CVC_COM_RX_BATTERY_STATUS    14u   /* CAN 0x303 */
#define CVC_COM_RX_LIGHT_STATUS    15u   /* CAN 0x400 */
#define CVC_COM_RX_INDICATOR_STATE    16u   /* CAN 0x401 */
#define CVC_COM_RX_DOOR_LOCK_STATUS    17u   /* CAN 0x402 */
#define CVC_COM_RX_UDS_RESP_TCU    18u   /* CAN 0x644 */
#define CVC_COM_RX_UDS_FUNC_REQUEST    19u   /* CAN 0x7DF */
#define CVC_COM_RX_UDS_PHYS_REQ_CVC    20u   /* CAN 0x7E0 */
#define CVC_COM_RX_UDS_PHYS_REQ_FZC    21u   /* CAN 0x7E1 */
#define CVC_COM_RX_UDS_PHYS_REQ_RZC    22u   /* CAN 0x7E2 */
#define CVC_COM_RX_UDS_PHYS_REQ_TCU    23u   /* CAN 0x7E3 */
#define CVC_COM_RX_UDS_RESP_FZC    24u   /* CAN 0x7E9 */
#define CVC_COM_RX_UDS_RESP_RZC    25u   /* CAN 0x7EA */

/* ====================================================================
 * Com Signal IDs (index into Com signal config table)
 * Use these instead of hardcoded numbers in Com_SendSignal/Com_ReceiveSignal
 * ==================================================================== */

#define CVC_COM_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID     0u   /* TX EStop_Broadcast */
#define CVC_COM_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER     1u   /* TX EStop_Broadcast */
#define CVC_COM_SIG_ESTOP_BROADCAST_E_2_E_CRC_8     2u   /* TX EStop_Broadcast */
#define CVC_COM_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE     3u   /* TX EStop_Broadcast */
#define CVC_COM_SIG_ESTOP_BROADCAST_ESTOP_SOURCE     4u   /* TX EStop_Broadcast */
#define CVC_COM_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID     5u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER     6u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_CVC_HEARTBEAT_E_2_E_CRC_8     7u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_CVC_HEARTBEAT_ECU_ID     8u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_CVC_HEARTBEAT_OPERATING_MODE     9u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_CVC_HEARTBEAT_FAULT_STATUS    10u   /* TX CVC_Heartbeat */
#define CVC_COM_SIG_VEHICLE_STATE_E_2_E_DATA_ID    11u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER    12u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_E_2_E_CRC_8    13u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_VEHICLE_STATE    14u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_FAULT_MASK    15u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_TORQUE_LIMIT    16u   /* TX Vehicle_State */
#define CVC_COM_SIG_VEHICLE_STATE_SPEED_LIMIT    17u   /* TX Vehicle_State */
#define CVC_COM_SIG_TORQUE_REQUEST_E_2_E_DATA_ID    18u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER    19u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_E_2_E_CRC_8    20u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_TORQUE_REQUEST    21u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_DIRECTION    22u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_1    23u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_2    24u   /* TX Torque_Request */
#define CVC_COM_SIG_TORQUE_REQUEST_PEDAL_FAULT    25u   /* TX Torque_Request */
#define CVC_COM_SIG_STEER_COMMAND_E_2_E_DATA_ID    26u   /* TX Steer_Command */
#define CVC_COM_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER    27u   /* TX Steer_Command */
#define CVC_COM_SIG_STEER_COMMAND_E_2_E_CRC_8    28u   /* TX Steer_Command */
#define CVC_COM_SIG_STEER_COMMAND_STEER_ANGLE_CMD    29u   /* TX Steer_Command */
#define CVC_COM_SIG_STEER_COMMAND_STEER_RATE_LIMIT    30u   /* TX Steer_Command */
#define CVC_COM_SIG_STEER_COMMAND_VEHICLE_STATE    31u   /* TX Steer_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    32u   /* TX Brake_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    33u   /* TX Brake_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_E_2_E_CRC_8    34u   /* TX Brake_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    35u   /* TX Brake_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_BRAKE_MODE    36u   /* TX Brake_Command */
#define CVC_COM_SIG_BRAKE_COMMAND_VEHICLE_STATE    37u   /* TX Brake_Command */
#define CVC_COM_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD    38u   /* TX Body_Control_Cmd */
#define CVC_COM_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD    39u   /* TX Body_Control_Cmd */
#define CVC_COM_SIG_BODY_CONTROL_CMD_HAZARD_CMD    40u   /* TX Body_Control_Cmd */
#define CVC_COM_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD    41u   /* TX Body_Control_Cmd */
#define CVC_COM_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD    42u   /* TX Body_Control_Cmd */
#define CVC_COM_SIG_DTC_BROADCAST_DTC_NUMBER    43u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_DTC_BROADCAST_DTC_STATUS    44u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_DTC_BROADCAST_ECU_SOURCE    45u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    46u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_0    47u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_1    48u   /* TX DTC_Broadcast */
#define CVC_COM_SIG_UDS_RESP_CVC_UDS_DATA    49u   /* TX UDS_Resp_CVC */
#define CVC_COM_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    50u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    51u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    52u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_FZC_HEARTBEAT_ECU_ID    53u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_FZC_HEARTBEAT_OPERATING_MODE    54u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_FZC_HEARTBEAT_FAULT_STATUS    55u   /* RX FZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID    56u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    57u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_E_2_E_CRC_8    58u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_ECU_ID    59u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_OPERATING_MODE    60u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_RZC_HEARTBEAT_FAULT_STATUS    61u   /* RX RZC_Heartbeat */
#define CVC_COM_SIG_SC_STATUS_SC_ALIVE_COUNTER    62u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_SC_CRC_8    63u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_SC_MODE    64u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_SC_FAULT_FLAGS    65u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_ECU_HEALTH    66u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_FAULT_REASON    67u   /* RX SC_Status */
#define CVC_COM_SIG_SC_STATUS_RELAY_STATE    68u   /* RX SC_Status */
#define CVC_COM_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    69u   /* RX ICU_Heartbeat */
#define CVC_COM_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    70u   /* RX ICU_Heartbeat */
#define CVC_COM_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    71u   /* RX ICU_Heartbeat */
#define CVC_COM_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    72u   /* RX ICU_Heartbeat */
#define CVC_COM_SIG_ICU_HEARTBEAT_ECU_ID    73u   /* RX ICU_Heartbeat */
#define CVC_COM_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID    74u   /* RX TCU_Heartbeat */
#define CVC_COM_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER    75u   /* RX TCU_Heartbeat */
#define CVC_COM_SIG_TCU_HEARTBEAT_E_2_E_CRC_8    76u   /* RX TCU_Heartbeat */
#define CVC_COM_SIG_TCU_HEARTBEAT_ALIVE_COUNTER    77u   /* RX TCU_Heartbeat */
#define CVC_COM_SIG_TCU_HEARTBEAT_ECU_ID    78u   /* RX TCU_Heartbeat */
#define CVC_COM_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    79u   /* RX BCM_Heartbeat */
#define CVC_COM_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    80u   /* RX BCM_Heartbeat */
#define CVC_COM_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    81u   /* RX BCM_Heartbeat */
#define CVC_COM_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    82u   /* RX BCM_Heartbeat */
#define CVC_COM_SIG_BCM_HEARTBEAT_ECU_ID    83u   /* RX BCM_Heartbeat */
#define CVC_COM_SIG_STEERING_STATUS_E_2_E_DATA_ID    84u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER    85u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_E_2_E_CRC_8    86u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_ACTUAL_ANGLE    87u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_COMMANDED_ANGLE    88u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_STEER_FAULT_STATUS    89u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_STEER_MODE    90u   /* RX Steering_Status */
#define CVC_COM_SIG_STEERING_STATUS_SERVO_CURRENT_M_A    91u   /* RX Steering_Status */
#define CVC_COM_SIG_BRAKE_STATUS_E_2_E_DATA_ID    92u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    93u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_E_2_E_CRC_8    94u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_BRAKE_POSITION    95u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    96u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    97u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    98u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_STATUS_BRAKE_MODE    99u   /* RX Brake_Status */
#define CVC_COM_SIG_BRAKE_FAULT_E_2_E_DATA_ID   100u   /* RX Brake_Fault */
#define CVC_COM_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER   101u   /* RX Brake_Fault */
#define CVC_COM_SIG_BRAKE_FAULT_E_2_E_CRC_8   102u   /* RX Brake_Fault */
#define CVC_COM_SIG_BRAKE_FAULT_FAULT_TYPE   103u   /* RX Brake_Fault */
#define CVC_COM_SIG_BRAKE_FAULT_COMMANDED_BRAKE   104u   /* RX Brake_Fault */
#define CVC_COM_SIG_BRAKE_FAULT_MEASURED_BRAKE   105u   /* RX Brake_Fault */
#define CVC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   106u   /* RX Motor_Cutoff_Req */
#define CVC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   107u   /* RX Motor_Cutoff_Req */
#define CVC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   108u   /* RX Motor_Cutoff_Req */
#define CVC_COM_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   109u   /* RX Motor_Cutoff_Req */
#define CVC_COM_SIG_MOTOR_CUTOFF_REQ_REASON   110u   /* RX Motor_Cutoff_Req */
#define CVC_COM_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID   111u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER   112u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_E_2_E_CRC_8   113u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_DISTANCE_CM   114u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH   115u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE   116u   /* RX Lidar_Distance */
#define CVC_COM_SIG_LIDAR_DISTANCE_SENSOR_STATUS   117u   /* RX Lidar_Distance */
#define CVC_COM_SIG_MOTOR_STATUS_E_2_E_DATA_ID   118u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   119u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_E_2_E_CRC_8   120u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_TORQUE_ECHO   121u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   122u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_MOTOR_DIRECTION   123u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_MOTOR_ENABLE   124u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   125u   /* RX Motor_Status */
#define CVC_COM_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   126u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   127u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_E_2_E_CRC_8   128u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_CURRENT_M_A   129u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   130u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_MOTOR_ENABLE   131u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   132u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_CURRENT_TORQUE_ECHO   133u   /* RX Motor_Current */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   134u   /* RX Motor_Temperature */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   135u   /* RX Motor_Temperature */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   136u   /* RX Motor_Temperature */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   137u   /* RX Motor_Temperature */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   138u   /* RX Motor_Temperature */
#define CVC_COM_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   139u   /* RX Motor_Temperature */
#define CVC_COM_SIG_BATTERY_STATUS_E_2_E_DATA_ID   140u   /* RX Battery_Status */
#define CVC_COM_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER   141u   /* RX Battery_Status */
#define CVC_COM_SIG_BATTERY_STATUS_E_2_E_CRC_8   142u   /* RX Battery_Status */
#define CVC_COM_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V   143u   /* RX Battery_Status */
#define CVC_COM_SIG_BATTERY_STATUS_BATTERY_STATUS   144u   /* RX Battery_Status */
#define CVC_COM_SIG_LIGHT_STATUS_HEADLIGHT_ON   145u   /* RX Light_Status */
#define CVC_COM_SIG_LIGHT_STATUS_TAIL_LIGHT_ON   146u   /* RX Light_Status */
#define CVC_COM_SIG_LIGHT_STATUS_FOG_LIGHT_ON   147u   /* RX Light_Status */
#define CVC_COM_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON   148u   /* RX Light_Status */
#define CVC_COM_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL   149u   /* RX Light_Status */
#define CVC_COM_SIG_INDICATOR_STATE_LEFT_INDICATOR   150u   /* RX Indicator_State */
#define CVC_COM_SIG_INDICATOR_STATE_RIGHT_INDICATOR   151u   /* RX Indicator_State */
#define CVC_COM_SIG_INDICATOR_STATE_HAZARD_ACTIVE   152u   /* RX Indicator_State */
#define CVC_COM_SIG_INDICATOR_STATE_BLINK_STATE   153u   /* RX Indicator_State */
#define CVC_COM_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK   154u   /* RX Door_Lock_Status */
#define CVC_COM_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK   155u   /* RX Door_Lock_Status */
#define CVC_COM_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK   156u   /* RX Door_Lock_Status */
#define CVC_COM_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK   157u   /* RX Door_Lock_Status */
#define CVC_COM_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK   158u   /* RX Door_Lock_Status */
#define CVC_COM_SIG_UDS_RESP_TCU_UDS_DATA   159u   /* RX UDS_Resp_TCU */
#define CVC_COM_SIG_UDS_FUNC_REQUEST_UDS_DATA   160u   /* RX UDS_Func_Request */
#define CVC_COM_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   161u   /* RX UDS_Phys_Req_CVC */
#define CVC_COM_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   162u   /* RX UDS_Phys_Req_FZC */
#define CVC_COM_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   163u   /* RX UDS_Phys_Req_RZC */
#define CVC_COM_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   164u   /* RX UDS_Phys_Req_TCU */
#define CVC_COM_SIG_UDS_RESP_FZC_UDS_DATA   165u   /* RX UDS_Resp_FZC */
#define CVC_COM_SIG_UDS_RESP_RZC_UDS_DATA   166u   /* RX UDS_Resp_RZC */
#define CVC_COM_SIG_COUNT   167u

/* ====================================================================
 * DTC Event IDs (Dem_EventIdType)
 * ==================================================================== */

#define CVC_DTC_PEDAL_PLAUSIBILITY     0u
#define CVC_DTC_PEDAL_STUCK     1u
#define CVC_DTC_PEDAL_RANGE     2u
#define CVC_DTC_COMM_FZC_TIMEOUT     3u
#define CVC_DTC_COMM_RZC_TIMEOUT     4u
#define CVC_DTC_COMM_SC_TIMEOUT     5u
#define CVC_DTC_VEHICLE_STATE     6u
#define CVC_DTC_ESTOP_FAULT     7u
#define CVC_DTC_MOTOR_OVERCURRENT     8u
#define CVC_DTC_MOTOR_OVERSPEED     9u
#define CVC_DTC_BATTERY_LOW    10u
#define CVC_DTC_BATTERY_CRITICAL    11u
#define CVC_DTC_STEERING_FAULT    12u
#define CVC_DTC_BRAKE_FAULT    13u
#define CVC_DTC_LIDAR_FAULT    14u
#define CVC_DTC_CAN_BUS_OFF    15u
#define CVC_DTC_SELF_TEST_FAIL    16u
#define CVC_DTC_WATCHDOG_FAULT    17u
#define CVC_DTC_SC_RELAY_KILL    18u

/* ====================================================================
 * E2E Data IDs
 * ==================================================================== */

#define CVC_E2E_ESTOP_DATA_ID  0x01u
#define CVC_E2E_VEHICLE_STATE_DATA_ID  0x02u
#define CVC_E2E_TORQUE_DATA_ID  0x03u
#define CVC_E2E_HEARTBEAT_DATA_ID  0x04u
#define CVC_E2E_STEER_CMD_DATA_ID  0x05u
#define CVC_E2E_BRAKE_CMD_DATA_ID  0x06u

/* ====================================================================
 * Enums
 * ==================================================================== */

#define CVC_STATE_INIT     0u
#define CVC_STATE_SELF_TEST     1u
#define CVC_STATE_RUN     2u
#define CVC_STATE_DEGRADED     3u
#define CVC_STATE_SAFE_STOP     4u
#define CVC_STATE_FAULT     5u
#define CVC_COMM_OK     0u
#define CVC_COMM_TIMEOUT     1u
#define CVC_COMM_ERROR     2u

/* ====================================================================
 * Thresholds
 * ==================================================================== */

#define CVC_INIT_HOLD_CYCLES   500u
#define CVC_RTE_PERIOD_MS    10u
#define CVC_COMM_TIMEOUT_MS   100u
#define CVC_PEDAL_PLAUS_THRESHOLD   819u
#define CVC_PEDAL_STUCK_THRESHOLD    10u
#define CVC_FAULT_CONFIRM_THRESHOLD     3u
#define CVC_MOTOR_OVERCURRENT_LIMIT  4000u
#define CVC_MOTOR_OVERSPEED_LIMIT  6000u
#define CVC_BATTERY_LOW_THRESHOLD  2200u
#define CVC_BATTERY_CRITICAL_THRESHOLD  2000u

/* ====================================================================
 * Application-specific constants (hand-authored, not generated)
 * ==================================================================== */
#if __has_include("Cvc_App.h")
#include "Cvc_App.h"
#endif

#endif /* CVC_CFG_H */
