/**
 * @file    Com_Cfg_Rzc.c
 * @brief   Com module configuration for RZC — TX/RX PDUs and signal mappings
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#include "Com.h"
#include "Rzc_Cfg.h"

/* ==================================================================
 * Shadow Buffers (static RAM for signal read/write)
 * ================================================================== */

/* TX signal buffers */
static uint8_t  sig_tx_rzc_heartbeat_e2e_dataid;
static uint8_t  sig_tx_rzc_heartbeat_e2e_alivecounter;
static uint8_t  sig_tx_rzc_heartbeat_e2e_crc8;
static uint8_t  sig_tx_rzc_heartbeat_ecu_id;
static uint8_t  sig_tx_rzc_heartbeat_operatingmode;
static uint8_t  sig_tx_rzc_heartbeat_faultstatus;
static uint8_t  sig_tx_motor_status_e2e_dataid;
static uint8_t  sig_tx_motor_status_e2e_alivecounter;
static uint8_t  sig_tx_motor_status_e2e_crc8;
static uint8_t  sig_tx_motor_status_torqueecho;
static uint16_t  sig_tx_motor_status_motorspeed_rpm;
static uint8_t  sig_tx_motor_status_motordirection;
static uint8_t  sig_tx_motor_status_motorenable;
static uint8_t  sig_tx_motor_status_motorfaultstatus;
static uint8_t  sig_tx_motor_current_e2e_dataid;
static uint8_t  sig_tx_motor_current_e2e_alivecounter;
static uint8_t  sig_tx_motor_current_e2e_crc8;
static uint16_t  sig_tx_motor_current_current_ma;
static boolean  sig_tx_motor_current_currentdirection;
static boolean  sig_tx_motor_current_motorenable;
static boolean  sig_tx_motor_current_overcurrentflag;
static uint8_t  sig_tx_motor_current_torqueecho;
static uint8_t  sig_tx_motor_temperature_e2e_dataid;
static uint8_t  sig_tx_motor_temperature_e2e_alivecounter;
static uint8_t  sig_tx_motor_temperature_e2e_crc8;
static uint16_t  sig_tx_motor_temperature_windingtemp1_c;
static uint16_t  sig_tx_motor_temperature_windingtemp2_c;
static uint8_t  sig_tx_motor_temperature_deratingpercent;
static uint8_t  sig_tx_battery_status_e2e_dataid;
static uint8_t  sig_tx_battery_status_e2e_alivecounter;
static uint8_t  sig_tx_battery_status_e2e_crc8;
static uint16_t  sig_tx_battery_status_batteryvoltage_mv;
static uint8_t  sig_tx_battery_status_batterystatus;
static uint32_t  sig_tx_dtc_broadcast_dtc_number;
static uint8_t  sig_tx_dtc_broadcast_dtc_status;
static uint8_t  sig_tx_dtc_broadcast_ecu_source;
static uint8_t  sig_tx_dtc_broadcast_occurrencecount;
static uint8_t  sig_tx_dtc_broadcast_freezeframe0;
static uint8_t  sig_tx_dtc_broadcast_freezeframe1;
static uint32_t  sig_tx_uds_resp_rzc_uds_data;

/* RX signal buffers */
static uint8_t  sig_rx_estop_broadcast_e2e_dataid;
static uint8_t  sig_rx_estop_broadcast_e2e_alivecounter;
static uint8_t  sig_rx_estop_broadcast_e2e_crc8;
static uint8_t  sig_rx_estop_broadcast_estop_active;
static uint8_t  sig_rx_estop_broadcast_estop_source;
static uint8_t  sig_rx_cvc_heartbeat_e2e_dataid;
static uint8_t  sig_rx_cvc_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_cvc_heartbeat_e2e_crc8;
static uint8_t  sig_rx_cvc_heartbeat_ecu_id;
static uint8_t  sig_rx_cvc_heartbeat_operatingmode;
static uint8_t  sig_rx_cvc_heartbeat_faultstatus;
static uint8_t  sig_rx_fzc_heartbeat_e2e_dataid;
static uint8_t  sig_rx_fzc_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_fzc_heartbeat_e2e_crc8;
static uint8_t  sig_rx_fzc_heartbeat_ecu_id;
static uint8_t  sig_rx_fzc_heartbeat_operatingmode;
static uint8_t  sig_rx_fzc_heartbeat_faultstatus;
static uint8_t  sig_rx_sc_status_sc_alivecounter;
static uint8_t  sig_rx_sc_status_sc_crc8;
static uint8_t  sig_rx_sc_status_sc_mode;
static uint8_t  sig_rx_sc_status_sc_faultflags;
static uint8_t  sig_rx_sc_status_ecu_health;
static uint8_t  sig_rx_sc_status_faultreason;
static boolean  sig_rx_sc_status_relaystate;
static uint8_t  sig_rx_icu_heartbeat_e2e_dataid;
static uint8_t  sig_rx_icu_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_icu_heartbeat_e2e_crc8;
static uint8_t  sig_rx_icu_heartbeat_alivecounter;
static uint8_t  sig_rx_icu_heartbeat_ecu_id;
static uint8_t  sig_rx_tcu_heartbeat_e2e_dataid;
static uint8_t  sig_rx_tcu_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_tcu_heartbeat_e2e_crc8;
static uint8_t  sig_rx_tcu_heartbeat_alivecounter;
static uint8_t  sig_rx_tcu_heartbeat_ecu_id;
static uint8_t  sig_rx_bcm_heartbeat_e2e_dataid;
static uint8_t  sig_rx_bcm_heartbeat_e2e_alivecounter;
static uint8_t  sig_rx_bcm_heartbeat_e2e_crc8;
static uint8_t  sig_rx_bcm_heartbeat_alivecounter;
static uint8_t  sig_rx_bcm_heartbeat_ecu_id;
static uint8_t  sig_rx_vehicle_state_e2e_dataid;
static uint8_t  sig_rx_vehicle_state_e2e_alivecounter;
static uint8_t  sig_rx_vehicle_state_e2e_crc8;
static uint8_t  sig_rx_vehicle_state_vehiclestate;
static uint16_t  sig_rx_vehicle_state_faultmask;
static uint8_t  sig_rx_vehicle_state_torquelimit;
static uint8_t  sig_rx_vehicle_state_speedlimit;
static uint8_t  sig_rx_torque_request_e2e_dataid;
static uint8_t  sig_rx_torque_request_e2e_alivecounter;
static uint8_t  sig_rx_torque_request_e2e_crc8;
static uint8_t  sig_rx_torque_request_torquerequest;
static uint8_t  sig_rx_torque_request_direction;
static uint16_t  sig_rx_torque_request_pedalposition1;
static uint16_t  sig_rx_torque_request_pedalposition2;
static boolean  sig_rx_torque_request_pedalfault;
static uint8_t  sig_rx_steer_command_e2e_dataid;
static uint8_t  sig_rx_steer_command_e2e_alivecounter;
static uint8_t  sig_rx_steer_command_e2e_crc8;
static uint16_t  sig_rx_steer_command_steeranglecmd;
static uint8_t  sig_rx_steer_command_steerratelimit;
static uint8_t  sig_rx_steer_command_vehiclestate;
static uint8_t  sig_rx_brake_command_e2e_dataid;
static uint8_t  sig_rx_brake_command_e2e_alivecounter;
static uint8_t  sig_rx_brake_command_e2e_crc8;
static uint8_t  sig_rx_brake_command_brakeforcecmd;
static uint8_t  sig_rx_brake_command_brakemode;
static uint8_t  sig_rx_brake_command_vehiclestate;
static uint8_t  sig_rx_steering_status_e2e_dataid;
static uint8_t  sig_rx_steering_status_e2e_alivecounter;
static uint8_t  sig_rx_steering_status_e2e_crc8;
static uint16_t  sig_rx_steering_status_actualangle;
static uint16_t  sig_rx_steering_status_commandedangle;
static uint8_t  sig_rx_steering_status_steerfaultstatus;
static uint8_t  sig_rx_steering_status_steermode;
static uint8_t  sig_rx_steering_status_servocurrent_ma;
static uint8_t  sig_rx_brake_status_e2e_dataid;
static uint8_t  sig_rx_brake_status_e2e_alivecounter;
static uint8_t  sig_rx_brake_status_e2e_crc8;
static uint8_t  sig_rx_brake_status_brakeposition;
static uint8_t  sig_rx_brake_status_brakecommandecho;
static uint16_t  sig_rx_brake_status_servocurrent_ma;
static uint8_t  sig_rx_brake_status_brakefaultstatus;
static uint8_t  sig_rx_brake_status_brakemode;
static uint8_t  sig_rx_brake_fault_e2e_dataid;
static uint8_t  sig_rx_brake_fault_e2e_alivecounter;
static uint8_t  sig_rx_brake_fault_e2e_crc8;
static uint8_t  sig_rx_brake_fault_faulttype;
static uint8_t  sig_rx_brake_fault_commandedbrake;
static uint8_t  sig_rx_brake_fault_measuredbrake;
static uint8_t  sig_rx_motor_cutoff_req_e2e_dataid;
static uint8_t  sig_rx_motor_cutoff_req_e2e_alivecounter;
static uint8_t  sig_rx_motor_cutoff_req_e2e_crc8;
static uint8_t  sig_rx_motor_cutoff_req_requesttype;
static uint8_t  sig_rx_motor_cutoff_req_reason;
static uint8_t  sig_rx_lidar_distance_e2e_dataid;
static uint8_t  sig_rx_lidar_distance_e2e_alivecounter;
static uint8_t  sig_rx_lidar_distance_e2e_crc8;
static uint16_t  sig_rx_lidar_distance_distance_cm;
static uint16_t  sig_rx_lidar_distance_signalstrength;
static uint8_t  sig_rx_lidar_distance_obstaclezone;
static uint8_t  sig_rx_lidar_distance_sensorstatus;
static uint8_t  sig_rx_body_control_cmd_headlightcmd;
static boolean  sig_rx_body_control_cmd_taillightcmd;
static boolean  sig_rx_body_control_cmd_hazardcmd;
static uint8_t  sig_rx_body_control_cmd_turnsignalcmd;
static boolean  sig_rx_body_control_cmd_doorlockcmd;
static boolean  sig_rx_light_status_headlighton;
static boolean  sig_rx_light_status_taillighton;
static boolean  sig_rx_light_status_foglighton;
static boolean  sig_rx_light_status_brakelighton;
static uint8_t  sig_rx_light_status_headlightlevel;
static boolean  sig_rx_indicator_state_leftindicator;
static boolean  sig_rx_indicator_state_rightindicator;
static boolean  sig_rx_indicator_state_hazardactive;
static boolean  sig_rx_indicator_state_blinkstate;
static boolean  sig_rx_door_lock_status_frontleftlock;
static boolean  sig_rx_door_lock_status_frontrightlock;
static boolean  sig_rx_door_lock_status_rearleftlock;
static boolean  sig_rx_door_lock_status_rearrightlock;
static boolean  sig_rx_door_lock_status_centrallock;
static uint32_t  sig_rx_dtc_broadcast_dtc_number;
static uint8_t  sig_rx_dtc_broadcast_dtc_status;
static uint8_t  sig_rx_dtc_broadcast_ecu_source;
static uint8_t  sig_rx_dtc_broadcast_occurrencecount;
static uint8_t  sig_rx_dtc_broadcast_freezeframe0;
static uint8_t  sig_rx_dtc_broadcast_freezeframe1;
static uint32_t  sig_rx_uds_resp_tcu_uds_data;
static uint32_t  sig_rx_uds_func_request_uds_data;
static uint32_t  sig_rx_uds_phys_req_cvc_uds_data;
static uint32_t  sig_rx_uds_phys_req_fzc_uds_data;
static uint32_t  sig_rx_uds_phys_req_rzc_uds_data;
static uint32_t  sig_rx_uds_phys_req_tcu_uds_data;
static uint32_t  sig_rx_uds_resp_cvc_uds_data;
static uint32_t  sig_rx_uds_resp_fzc_uds_data;

/* ==================================================================
 * Signal Configuration Table
 * Maps signal ID -> bit position, size, type, parent PDU, shadow buffer
 * ================================================================== */

static const Com_SignalConfigType rzc_signal_config[] = {
    /* TX signals */
    /* id, bitPos, bitSize, type,       pduId,                      shadowBuf */
    {  0u,    0u,     4u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_e2e_dataid },
    {  1u,    4u,     4u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_e2e_alivecounter },
    {  2u,    8u,     8u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_e2e_crc8 },
    {  3u,   16u,     8u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_ecu_id },
    {  4u,   24u,     4u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_operatingmode },
    {  5u,   28u,     4u, COM_UINT8, RZC_COM_TX_RZC_HEARTBEAT, &sig_tx_rzc_heartbeat_faultstatus },
    {  6u,    0u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_e2e_dataid },
    {  7u,    4u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_e2e_alivecounter },
    {  8u,    8u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_e2e_crc8 },
    {  9u,   16u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_torqueecho },
    { 10u,   24u,    16u, COM_UINT16, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_motorspeed_rpm },
    { 11u,   40u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_motordirection },
    { 12u,   48u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_motorenable },
    { 13u,   56u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_STATUS, &sig_tx_motor_status_motorfaultstatus },
    { 14u,    0u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_e2e_dataid },
    { 15u,    4u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_e2e_alivecounter },
    { 16u,    8u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_e2e_crc8 },
    { 17u,   16u,    16u, COM_UINT16, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_current_ma },
    { 18u,   32u,     1u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_currentdirection },
    { 19u,   33u,     1u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_motorenable },
    { 20u,   34u,     1u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_overcurrentflag },
    { 21u,   35u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_CURRENT, &sig_tx_motor_current_torqueecho },
    { 22u,    0u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_e2e_dataid },
    { 23u,    4u,     4u, COM_UINT8, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_e2e_alivecounter },
    { 24u,    8u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_e2e_crc8 },
    { 25u,   16u,    16u, COM_UINT16, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_windingtemp1_c },
    { 26u,   32u,    16u, COM_UINT16, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_windingtemp2_c },
    { 27u,   48u,     8u, COM_UINT8, RZC_COM_TX_MOTOR_TEMPERATURE, &sig_tx_motor_temperature_deratingpercent },
    { 28u,    0u,     4u, COM_UINT8, RZC_COM_TX_BATTERY_STATUS, &sig_tx_battery_status_e2e_dataid },
    { 29u,    4u,     4u, COM_UINT8, RZC_COM_TX_BATTERY_STATUS, &sig_tx_battery_status_e2e_alivecounter },
    { 30u,    8u,     8u, COM_UINT8, RZC_COM_TX_BATTERY_STATUS, &sig_tx_battery_status_e2e_crc8 },
    { 31u,   16u,    16u, COM_UINT16, RZC_COM_TX_BATTERY_STATUS, &sig_tx_battery_status_batteryvoltage_mv },
    { 32u,   32u,     8u, COM_UINT8, RZC_COM_TX_BATTERY_STATUS, &sig_tx_battery_status_batterystatus },
    { 33u,    7u,    24u, COM_UINT32, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_dtc_number },
    { 34u,   24u,     8u, COM_UINT8, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_dtc_status },
    { 35u,   32u,     8u, COM_UINT8, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_ecu_source },
    { 36u,   40u,     8u, COM_UINT8, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_occurrencecount },
    { 37u,   48u,     8u, COM_UINT8, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe0 },
    { 38u,   56u,     8u, COM_UINT8, RZC_COM_TX_DTC_BROADCAST, &sig_tx_dtc_broadcast_freezeframe1 },
    { 39u,    0u,    64u, COM_UINT32, RZC_COM_TX_UDS_RESP_RZC, &sig_tx_uds_resp_rzc_uds_data },

    /* RX signals */
    { 40u,    0u,     4u, COM_UINT8, RZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_dataid },
    { 41u,    4u,     4u, COM_UINT8, RZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_alivecounter },
    { 42u,    8u,     8u, COM_UINT8, RZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_e2e_crc8 },
    { 43u,   16u,     8u, COM_UINT8, RZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_estop_active },
    { 44u,   24u,     8u, COM_UINT8, RZC_COM_RX_ESTOP_BROADCAST, &sig_rx_estop_broadcast_estop_source },
    { 45u,    0u,     4u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_dataid },
    { 46u,    4u,     4u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_alivecounter },
    { 47u,    8u,     8u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_e2e_crc8 },
    { 48u,   16u,     8u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_ecu_id },
    { 49u,   24u,     4u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_operatingmode },
    { 50u,   28u,     4u, COM_UINT8, RZC_COM_RX_CVC_HEARTBEAT, &sig_rx_cvc_heartbeat_faultstatus },
    { 51u,    0u,     4u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_e2e_dataid },
    { 52u,    4u,     4u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_e2e_alivecounter },
    { 53u,    8u,     8u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_e2e_crc8 },
    { 54u,   16u,     8u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_ecu_id },
    { 55u,   24u,     4u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_operatingmode },
    { 56u,   28u,     4u, COM_UINT8, RZC_COM_RX_FZC_HEARTBEAT, &sig_rx_fzc_heartbeat_faultstatus },
    { 57u,    0u,     8u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_sc_alivecounter },
    { 58u,    8u,     8u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_sc_crc8 },
    { 59u,   16u,     4u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_sc_mode },
    { 60u,   20u,     4u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_sc_faultflags },
    { 61u,   24u,     3u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_ecu_health },
    { 62u,   27u,     4u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_faultreason },
    { 63u,   31u,     1u, COM_UINT8, RZC_COM_RX_SC_STATUS, &sig_rx_sc_status_relaystate },
    { 64u,    0u,     4u, COM_UINT8, RZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_dataid },
    { 65u,    4u,     4u, COM_UINT8, RZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_alivecounter },
    { 66u,    8u,     8u, COM_UINT8, RZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_e2e_crc8 },
    { 67u,   16u,     8u, COM_UINT8, RZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_alivecounter },
    { 68u,   24u,     8u, COM_UINT8, RZC_COM_RX_ICU_HEARTBEAT, &sig_rx_icu_heartbeat_ecu_id },
    { 69u,    0u,     4u, COM_UINT8, RZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_dataid },
    { 70u,    4u,     4u, COM_UINT8, RZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_alivecounter },
    { 71u,    8u,     8u, COM_UINT8, RZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_e2e_crc8 },
    { 72u,   16u,     8u, COM_UINT8, RZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_alivecounter },
    { 73u,   24u,     8u, COM_UINT8, RZC_COM_RX_TCU_HEARTBEAT, &sig_rx_tcu_heartbeat_ecu_id },
    { 74u,    0u,     4u, COM_UINT8, RZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_dataid },
    { 75u,    4u,     4u, COM_UINT8, RZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_alivecounter },
    { 76u,    8u,     8u, COM_UINT8, RZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_e2e_crc8 },
    { 77u,   16u,     8u, COM_UINT8, RZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_alivecounter },
    { 78u,   24u,     8u, COM_UINT8, RZC_COM_RX_BCM_HEARTBEAT, &sig_rx_bcm_heartbeat_ecu_id },
    { 79u,    0u,     4u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_dataid },
    { 80u,    4u,     4u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_alivecounter },
    { 81u,    8u,     8u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_e2e_crc8 },
    { 82u,   16u,     4u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_vehiclestate },
    { 83u,   20u,    12u, COM_UINT16, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_faultmask },
    { 84u,   32u,     8u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_torquelimit },
    { 85u,   40u,     8u, COM_UINT8, RZC_COM_RX_VEHICLE_STATE, &sig_rx_vehicle_state_speedlimit },
    { 86u,    0u,     4u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_dataid },
    { 87u,    4u,     4u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_alivecounter },
    { 88u,    8u,     8u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_e2e_crc8 },
    { 89u,   16u,     8u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_torquerequest },
    { 90u,   24u,     2u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_direction },
    { 91u,   26u,    14u, COM_UINT16, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition1 },
    { 92u,   40u,    14u, COM_UINT16, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalposition2 },
    { 93u,   54u,     1u, COM_UINT8, RZC_COM_RX_TORQUE_REQUEST, &sig_rx_torque_request_pedalfault },
    { 94u,    0u,     4u, COM_UINT8, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_dataid },
    { 95u,    4u,     4u, COM_UINT8, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_alivecounter },
    { 96u,    8u,     8u, COM_UINT8, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_e2e_crc8 },
    { 97u,   16u,    16u, COM_UINT16, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steeranglecmd },
    { 98u,   32u,     8u, COM_UINT8, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_steerratelimit },
    { 99u,   40u,     4u, COM_UINT8, RZC_COM_RX_STEER_COMMAND, &sig_rx_steer_command_vehiclestate },
    { 100u,    0u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_dataid },
    { 101u,    4u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_alivecounter },
    { 102u,    8u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_e2e_crc8 },
    { 103u,   16u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakeforcecmd },
    { 104u,   24u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_brakemode },
    { 105u,   28u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_COMMAND, &sig_rx_brake_command_vehiclestate },
    { 106u,    0u,     4u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_e2e_dataid },
    { 107u,    4u,     4u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_e2e_alivecounter },
    { 108u,    8u,     8u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_e2e_crc8 },
    { 109u,   16u,    16u, COM_UINT16, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_actualangle },
    { 110u,   32u,    16u, COM_UINT16, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_commandedangle },
    { 111u,   48u,     4u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_steerfaultstatus },
    { 112u,   52u,     4u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_steermode },
    { 113u,   56u,     8u, COM_UINT8, RZC_COM_RX_STEERING_STATUS, &sig_rx_steering_status_servocurrent_ma },
    { 114u,    0u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_e2e_dataid },
    { 115u,    4u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_e2e_alivecounter },
    { 116u,    8u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_e2e_crc8 },
    { 117u,   16u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_brakeposition },
    { 118u,   24u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_brakecommandecho },
    { 119u,   32u,    16u, COM_UINT16, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_servocurrent_ma },
    { 120u,   48u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_brakefaultstatus },
    { 121u,   52u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_STATUS, &sig_rx_brake_status_brakemode },
    { 122u,    0u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_e2e_dataid },
    { 123u,    4u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_e2e_alivecounter },
    { 124u,    8u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_e2e_crc8 },
    { 125u,   16u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_faulttype },
    { 126u,   20u,     8u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_commandedbrake },
    { 127u,   28u,     4u, COM_UINT8, RZC_COM_RX_BRAKE_FAULT, &sig_rx_brake_fault_measuredbrake },
    { 128u,    0u,     4u, COM_UINT8, RZC_COM_RX_MOTOR_CUTOFF_REQ, &sig_rx_motor_cutoff_req_e2e_dataid },
    { 129u,    4u,     4u, COM_UINT8, RZC_COM_RX_MOTOR_CUTOFF_REQ, &sig_rx_motor_cutoff_req_e2e_alivecounter },
    { 130u,    8u,     8u, COM_UINT8, RZC_COM_RX_MOTOR_CUTOFF_REQ, &sig_rx_motor_cutoff_req_e2e_crc8 },
    { 131u,   16u,     4u, COM_UINT8, RZC_COM_RX_MOTOR_CUTOFF_REQ, &sig_rx_motor_cutoff_req_requesttype },
    { 132u,   20u,     4u, COM_UINT8, RZC_COM_RX_MOTOR_CUTOFF_REQ, &sig_rx_motor_cutoff_req_reason },
    { 133u,    0u,     4u, COM_UINT8, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_e2e_dataid },
    { 134u,    4u,     4u, COM_UINT8, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_e2e_alivecounter },
    { 135u,    8u,     8u, COM_UINT8, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_e2e_crc8 },
    { 136u,   16u,    16u, COM_UINT16, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_distance_cm },
    { 137u,   32u,    16u, COM_UINT16, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_signalstrength },
    { 138u,   48u,     4u, COM_UINT8, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_obstaclezone },
    { 139u,   52u,     4u, COM_UINT8, RZC_COM_RX_LIDAR_DISTANCE, &sig_rx_lidar_distance_sensorstatus },
    { 140u,    0u,     2u, COM_UINT8, RZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_headlightcmd },
    { 141u,    2u,     1u, COM_UINT8, RZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_taillightcmd },
    { 142u,    3u,     1u, COM_UINT8, RZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_hazardcmd },
    { 143u,    4u,     2u, COM_UINT8, RZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_turnsignalcmd },
    { 144u,    6u,     1u, COM_UINT8, RZC_COM_RX_BODY_CONTROL_CMD, &sig_rx_body_control_cmd_doorlockcmd },
    { 145u,    0u,     1u, COM_UINT8, RZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlighton },
    { 146u,    1u,     1u, COM_UINT8, RZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_taillighton },
    { 147u,    2u,     1u, COM_UINT8, RZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_foglighton },
    { 148u,    3u,     1u, COM_UINT8, RZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_brakelighton },
    { 149u,    4u,     2u, COM_UINT8, RZC_COM_RX_LIGHT_STATUS, &sig_rx_light_status_headlightlevel },
    { 150u,    0u,     1u, COM_UINT8, RZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_leftindicator },
    { 151u,    1u,     1u, COM_UINT8, RZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_rightindicator },
    { 152u,    2u,     1u, COM_UINT8, RZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_hazardactive },
    { 153u,    3u,     1u, COM_UINT8, RZC_COM_RX_INDICATOR_STATE, &sig_rx_indicator_state_blinkstate },
    { 154u,    0u,     1u, COM_UINT8, RZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontleftlock },
    { 155u,    1u,     1u, COM_UINT8, RZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_frontrightlock },
    { 156u,    2u,     1u, COM_UINT8, RZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearleftlock },
    { 157u,    3u,     1u, COM_UINT8, RZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_rearrightlock },
    { 158u,    4u,     1u, COM_UINT8, RZC_COM_RX_DOOR_LOCK_STATUS, &sig_rx_door_lock_status_centrallock },
    { 159u,    7u,    24u, COM_UINT32, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_dtc_number },
    { 160u,   24u,     8u, COM_UINT8, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_dtc_status },
    { 161u,   32u,     8u, COM_UINT8, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_ecu_source },
    { 162u,   40u,     8u, COM_UINT8, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_occurrencecount },
    { 163u,   48u,     8u, COM_UINT8, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe0 },
    { 164u,   56u,     8u, COM_UINT8, RZC_COM_RX_DTC_BROADCAST, &sig_rx_dtc_broadcast_freezeframe1 },
    { 165u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_RESP_TCU, &sig_rx_uds_resp_tcu_uds_data },
    { 166u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_FUNC_REQUEST, &sig_rx_uds_func_request_uds_data },
    { 167u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_PHYS_REQ_CVC, &sig_rx_uds_phys_req_cvc_uds_data },
    { 168u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_PHYS_REQ_FZC, &sig_rx_uds_phys_req_fzc_uds_data },
    { 169u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_PHYS_REQ_RZC, &sig_rx_uds_phys_req_rzc_uds_data },
    { 170u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_PHYS_REQ_TCU, &sig_rx_uds_phys_req_tcu_uds_data },
    { 171u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_RESP_CVC, &sig_rx_uds_resp_cvc_uds_data },
    { 172u,    0u,    64u, COM_UINT32, RZC_COM_RX_UDS_RESP_FZC, &sig_rx_uds_resp_fzc_uds_data },
};

#define RZC_COM_SIGNAL_COUNT  (sizeof(rzc_signal_config) / sizeof(rzc_signal_config[0]))

/* ==================================================================
 * TX PDU Configuration Table
 * Maps PDU ID -> DLC, cycle time
 * PDU ID to CAN ID routing is handled by CanIf
 * ================================================================== */

static const Com_TxPduConfigType rzc_tx_pdu_config[] = {
    /* pduId,                      dlc, cycleMs */
    { RZC_COM_TX_RZC_HEARTBEAT,     4u,     0u },   /* CAN 0x012 */
    { RZC_COM_TX_MOTOR_STATUS,     8u,     0u },   /* CAN 0x300 */
    { RZC_COM_TX_MOTOR_CURRENT,     8u,     0u },   /* CAN 0x301 */
    { RZC_COM_TX_MOTOR_TEMPERATURE,     8u,     0u },   /* CAN 0x302 */
    { RZC_COM_TX_BATTERY_STATUS,     6u,     0u },   /* CAN 0x303 */
    { RZC_COM_TX_DTC_BROADCAST,     8u,     0u },   /* CAN 0x500 */
    { RZC_COM_TX_UDS_RESP_RZC,     8u,     0u },   /* CAN 0x7EA */
};

#define RZC_COM_TX_PDU_COUNT  (sizeof(rzc_tx_pdu_config) / sizeof(rzc_tx_pdu_config[0]))

/* ==================================================================
 * RX PDU Configuration Table
 * ================================================================== */

static const Com_RxPduConfigType rzc_rx_pdu_config[] = {
    /* pduId,                     dlc, timeoutMs */
    { RZC_COM_RX_ESTOP_BROADCAST,     4u,     0u },   /* CAN 0x001 */
    { RZC_COM_RX_CVC_HEARTBEAT,     4u,     0u },   /* CAN 0x010 */
    { RZC_COM_RX_FZC_HEARTBEAT,     4u,     0u },   /* CAN 0x011 */
    { RZC_COM_RX_SC_STATUS,     4u,     0u },   /* CAN 0x013 */
    { RZC_COM_RX_ICU_HEARTBEAT,     4u,     0u },   /* CAN 0x014 */
    { RZC_COM_RX_TCU_HEARTBEAT,     4u,     0u },   /* CAN 0x015 */
    { RZC_COM_RX_BCM_HEARTBEAT,     4u,     0u },   /* CAN 0x016 */
    { RZC_COM_RX_VEHICLE_STATE,     6u,     0u },   /* CAN 0x100 */
    { RZC_COM_RX_TORQUE_REQUEST,     8u,     0u },   /* CAN 0x101 */
    { RZC_COM_RX_STEER_COMMAND,     8u,     0u },   /* CAN 0x102 */
    { RZC_COM_RX_BRAKE_COMMAND,     8u,     0u },   /* CAN 0x103 */
    { RZC_COM_RX_STEERING_STATUS,     8u,     0u },   /* CAN 0x200 */
    { RZC_COM_RX_BRAKE_STATUS,     8u,     0u },   /* CAN 0x201 */
    { RZC_COM_RX_BRAKE_FAULT,     4u,     0u },   /* CAN 0x210 */
    { RZC_COM_RX_MOTOR_CUTOFF_REQ,     4u,     0u },   /* CAN 0x211 */
    { RZC_COM_RX_LIDAR_DISTANCE,     8u,     0u },   /* CAN 0x220 */
    { RZC_COM_RX_BODY_CONTROL_CMD,     4u,     0u },   /* CAN 0x350 */
    { RZC_COM_RX_LIGHT_STATUS,     4u,     0u },   /* CAN 0x400 */
    { RZC_COM_RX_INDICATOR_STATE,     4u,     0u },   /* CAN 0x401 */
    { RZC_COM_RX_DOOR_LOCK_STATUS,     2u,     0u },   /* CAN 0x402 */
    { RZC_COM_RX_DTC_BROADCAST,     8u,     0u },   /* CAN 0x500 */
    { RZC_COM_RX_UDS_RESP_TCU,     8u,     0u },   /* CAN 0x644 */
    { RZC_COM_RX_UDS_FUNC_REQUEST,     8u,     0u },   /* CAN 0x7DF */
    { RZC_COM_RX_UDS_PHYS_REQ_CVC,     8u,     0u },   /* CAN 0x7E0 */
    { RZC_COM_RX_UDS_PHYS_REQ_FZC,     8u,     0u },   /* CAN 0x7E1 */
    { RZC_COM_RX_UDS_PHYS_REQ_RZC,     8u,     0u },   /* CAN 0x7E2 */
    { RZC_COM_RX_UDS_PHYS_REQ_TCU,     8u,     0u },   /* CAN 0x7E3 */
    { RZC_COM_RX_UDS_RESP_CVC,     8u,     0u },   /* CAN 0x7E8 */
    { RZC_COM_RX_UDS_RESP_FZC,     8u,     0u },   /* CAN 0x7E9 */
};

#define RZC_COM_RX_PDU_COUNT  (sizeof(rzc_rx_pdu_config) / sizeof(rzc_rx_pdu_config[0]))

/* ==================================================================
 * Aggregate Com Configuration
 * ================================================================== */

const Com_ConfigType rzc_com_config = {
    .signalConfig = rzc_signal_config,
    .signalCount  = (uint8)RZC_COM_SIGNAL_COUNT,
    .txPduConfig  = rzc_tx_pdu_config,
    .txPduCount   = (uint8)RZC_COM_TX_PDU_COUNT,
    .rxPduConfig  = rzc_rx_pdu_config,
    .rxPduCount   = (uint8)RZC_COM_RX_PDU_COUNT,
};
