/**
 * @file    Rzc_Cfg.h
 * @brief   RZC configuration — all RZC-specific ID definitions
 *
 * GENERATED BY arxmlgen v1.0.0 -- DO NOT EDIT
 * Source: TaktflowSystem.arxml
 * Config: project.yaml
 *
 * @standard AUTOSAR, ISO 26262 Part 6
 */
#ifndef RZC_CFG_H
#define RZC_CFG_H

/* ====================================================================
 * RTE Signal IDs (offset 16 from BSW well-known)
 * ==================================================================== */

#define RZC_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    16u
#define RZC_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    17u
#define RZC_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    18u
#define RZC_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    19u
#define RZC_SIG_BCM_HEARTBEAT_ECU_ID    20u
#define RZC_SIG_BATTERY_STATUS_BATTERY_STATUS    21u
#define RZC_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V    22u
#define RZC_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER    23u
#define RZC_SIG_BATTERY_STATUS_E_2_E_CRC_8    24u
#define RZC_SIG_BATTERY_STATUS_E_2_E_DATA_ID    25u
#define RZC_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD    26u
#define RZC_SIG_BODY_CONTROL_CMD_HAZARD_CMD    27u
#define RZC_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD    28u
#define RZC_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD    29u
#define RZC_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD    30u
#define RZC_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD    31u
#define RZC_SIG_BRAKE_COMMAND_BRAKE_MODE    32u
#define RZC_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER    33u
#define RZC_SIG_BRAKE_COMMAND_E_2_E_CRC_8    34u
#define RZC_SIG_BRAKE_COMMAND_E_2_E_DATA_ID    35u
#define RZC_SIG_BRAKE_COMMAND_VEHICLE_STATE    36u
#define RZC_SIG_BRAKE_FAULT_COMMANDED_BRAKE    37u
#define RZC_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER    38u
#define RZC_SIG_BRAKE_FAULT_E_2_E_CRC_8    39u
#define RZC_SIG_BRAKE_FAULT_E_2_E_DATA_ID    40u
#define RZC_SIG_BRAKE_FAULT_FAULT_TYPE    41u
#define RZC_SIG_BRAKE_FAULT_MEASURED_BRAKE    42u
#define RZC_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO    43u
#define RZC_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS    44u
#define RZC_SIG_BRAKE_STATUS_BRAKE_MODE    45u
#define RZC_SIG_BRAKE_STATUS_BRAKE_POSITION    46u
#define RZC_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER    47u
#define RZC_SIG_BRAKE_STATUS_E_2_E_CRC_8    48u
#define RZC_SIG_BRAKE_STATUS_E_2_E_DATA_ID    49u
#define RZC_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A    50u
#define RZC_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    51u
#define RZC_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    52u
#define RZC_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    53u
#define RZC_SIG_CVC_HEARTBEAT_ECU_ID    54u
#define RZC_SIG_CVC_HEARTBEAT_FAULT_STATUS    55u
#define RZC_SIG_CVC_HEARTBEAT_OPERATING_MODE    56u
#define RZC_SIG_DTC_BROADCAST_DTC_NUMBER    57u
#define RZC_SIG_DTC_BROADCAST_DTC_STATUS    58u
#define RZC_SIG_DTC_BROADCAST_ECU_SOURCE    59u
#define RZC_SIG_DTC_BROADCAST_FREEZE_FRAME_0    60u
#define RZC_SIG_DTC_BROADCAST_FREEZE_FRAME_1    61u
#define RZC_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    62u
#define RZC_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK    63u
#define RZC_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK    64u
#define RZC_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK    65u
#define RZC_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK    66u
#define RZC_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK    67u
#define RZC_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    68u
#define RZC_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    69u
#define RZC_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    70u
#define RZC_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    71u
#define RZC_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    72u
#define RZC_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    73u
#define RZC_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    74u
#define RZC_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    75u
#define RZC_SIG_FZC_HEARTBEAT_ECU_ID    76u
#define RZC_SIG_FZC_HEARTBEAT_FAULT_STATUS    77u
#define RZC_SIG_FZC_HEARTBEAT_OPERATING_MODE    78u
#define RZC_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    79u
#define RZC_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    80u
#define RZC_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    81u
#define RZC_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    82u
#define RZC_SIG_ICU_HEARTBEAT_ECU_ID    83u
#define RZC_SIG_INDICATOR_STATE_BLINK_STATE    84u
#define RZC_SIG_INDICATOR_STATE_HAZARD_ACTIVE    85u
#define RZC_SIG_INDICATOR_STATE_LEFT_INDICATOR    86u
#define RZC_SIG_INDICATOR_STATE_RIGHT_INDICATOR    87u
#define RZC_SIG_LIDAR_DISTANCE_DISTANCE_CM    88u
#define RZC_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER    89u
#define RZC_SIG_LIDAR_DISTANCE_E_2_E_CRC_8    90u
#define RZC_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID    91u
#define RZC_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE    92u
#define RZC_SIG_LIDAR_DISTANCE_SENSOR_STATUS    93u
#define RZC_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH    94u
#define RZC_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON    95u
#define RZC_SIG_LIGHT_STATUS_FOG_LIGHT_ON    96u
#define RZC_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL    97u
#define RZC_SIG_LIGHT_STATUS_HEADLIGHT_ON    98u
#define RZC_SIG_LIGHT_STATUS_TAIL_LIGHT_ON    99u
#define RZC_SIG_MOTOR_CURRENT_CURRENT_DIRECTION   100u
#define RZC_SIG_MOTOR_CURRENT_CURRENT_M_A   101u
#define RZC_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER   102u
#define RZC_SIG_MOTOR_CURRENT_E_2_E_CRC_8   103u
#define RZC_SIG_MOTOR_CURRENT_E_2_E_DATA_ID   104u
#define RZC_SIG_MOTOR_CURRENT_MOTOR_ENABLE   105u
#define RZC_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG   106u
#define RZC_SIG_MOTOR_CURRENT_TORQUE_ECHO   107u
#define RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   108u
#define RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   109u
#define RZC_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   110u
#define RZC_SIG_MOTOR_CUTOFF_REQ_REASON   111u
#define RZC_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   112u
#define RZC_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER   113u
#define RZC_SIG_MOTOR_STATUS_E_2_E_CRC_8   114u
#define RZC_SIG_MOTOR_STATUS_E_2_E_DATA_ID   115u
#define RZC_SIG_MOTOR_STATUS_MOTOR_DIRECTION   116u
#define RZC_SIG_MOTOR_STATUS_MOTOR_ENABLE   117u
#define RZC_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS   118u
#define RZC_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM   119u
#define RZC_SIG_MOTOR_STATUS_TORQUE_ECHO   120u
#define RZC_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT   121u
#define RZC_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER   122u
#define RZC_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8   123u
#define RZC_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID   124u
#define RZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C   125u
#define RZC_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C   126u
#define RZC_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER   127u
#define RZC_SIG_RZC_HEARTBEAT_E_2_E_CRC_8   128u
#define RZC_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID   129u
#define RZC_SIG_RZC_HEARTBEAT_ECU_ID   130u
#define RZC_SIG_RZC_HEARTBEAT_FAULT_STATUS   131u
#define RZC_SIG_RZC_HEARTBEAT_OPERATING_MODE   132u
#define RZC_SIG_SC_STATUS_ECU_HEALTH   133u
#define RZC_SIG_SC_STATUS_FAULT_REASON   134u
#define RZC_SIG_SC_STATUS_RELAY_STATE   135u
#define RZC_SIG_SC_STATUS_SC_ALIVE_COUNTER   136u
#define RZC_SIG_SC_STATUS_SC_CRC_8   137u
#define RZC_SIG_SC_STATUS_SC_FAULT_FLAGS   138u
#define RZC_SIG_SC_STATUS_SC_MODE   139u
#define RZC_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER   140u
#define RZC_SIG_STEER_COMMAND_E_2_E_CRC_8   141u
#define RZC_SIG_STEER_COMMAND_E_2_E_DATA_ID   142u
#define RZC_SIG_STEER_COMMAND_STEER_ANGLE_CMD   143u
#define RZC_SIG_STEER_COMMAND_STEER_RATE_LIMIT   144u
#define RZC_SIG_STEER_COMMAND_VEHICLE_STATE   145u
#define RZC_SIG_STEERING_STATUS_ACTUAL_ANGLE   146u
#define RZC_SIG_STEERING_STATUS_COMMANDED_ANGLE   147u
#define RZC_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER   148u
#define RZC_SIG_STEERING_STATUS_E_2_E_CRC_8   149u
#define RZC_SIG_STEERING_STATUS_E_2_E_DATA_ID   150u
#define RZC_SIG_STEERING_STATUS_SERVO_CURRENT_M_A   151u
#define RZC_SIG_STEERING_STATUS_STEER_FAULT_STATUS   152u
#define RZC_SIG_STEERING_STATUS_STEER_MODE   153u
#define RZC_SIG_TCU_HEARTBEAT_ALIVE_COUNTER   154u
#define RZC_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER   155u
#define RZC_SIG_TCU_HEARTBEAT_E_2_E_CRC_8   156u
#define RZC_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID   157u
#define RZC_SIG_TCU_HEARTBEAT_ECU_ID   158u
#define RZC_SIG_TORQUE_REQUEST_DIRECTION   159u
#define RZC_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER   160u
#define RZC_SIG_TORQUE_REQUEST_E_2_E_CRC_8   161u
#define RZC_SIG_TORQUE_REQUEST_E_2_E_DATA_ID   162u
#define RZC_SIG_TORQUE_REQUEST_PEDAL_FAULT   163u
#define RZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_1   164u
#define RZC_SIG_TORQUE_REQUEST_PEDAL_POSITION_2   165u
#define RZC_SIG_TORQUE_REQUEST_TORQUE_REQUEST   166u
#define RZC_SIG_UDS_FUNC_REQUEST_UDS_DATA   167u
#define RZC_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   168u
#define RZC_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   169u
#define RZC_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   170u
#define RZC_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   171u
#define RZC_SIG_UDS_RESP_CVC_UDS_DATA   172u
#define RZC_SIG_UDS_RESP_FZC_UDS_DATA   173u
#define RZC_SIG_UDS_RESP_RZC_UDS_DATA   174u
#define RZC_SIG_UDS_RESP_TCU_UDS_DATA   175u
#define RZC_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER   176u
#define RZC_SIG_VEHICLE_STATE_E_2_E_CRC_8   177u
#define RZC_SIG_VEHICLE_STATE_E_2_E_DATA_ID   178u
#define RZC_SIG_VEHICLE_STATE_FAULT_MASK   179u
#define RZC_SIG_VEHICLE_STATE_SPEED_LIMIT   180u
#define RZC_SIG_VEHICLE_STATE_TORQUE_LIMIT   181u
#define RZC_SIG_VEHICLE_STATE_VEHICLE_STATE   182u
#define RZC_SIG_COUNT   183u

/* ====================================================================
 * Com TX PDU IDs
 * ==================================================================== */

#define RZC_COM_TX_RZC_HEARTBEAT     0u   /* CAN 0x012 */
#define RZC_COM_TX_MOTOR_STATUS     1u   /* CAN 0x300 */
#define RZC_COM_TX_MOTOR_CURRENT     2u   /* CAN 0x301 */
#define RZC_COM_TX_MOTOR_TEMPERATURE     3u   /* CAN 0x302 */
#define RZC_COM_TX_BATTERY_STATUS     4u   /* CAN 0x303 */
#define RZC_COM_TX_DTC_BROADCAST     5u   /* CAN 0x500 */
#define RZC_COM_TX_UDS_RESP_RZC     6u   /* CAN 0x7EA */

/* ====================================================================
 * Com RX PDU IDs
 * ==================================================================== */

#define RZC_COM_RX_ESTOP_BROADCAST     0u   /* CAN 0x001 */
#define RZC_COM_RX_CVC_HEARTBEAT     1u   /* CAN 0x010 */
#define RZC_COM_RX_FZC_HEARTBEAT     2u   /* CAN 0x011 */
#define RZC_COM_RX_SC_STATUS     3u   /* CAN 0x013 */
#define RZC_COM_RX_ICU_HEARTBEAT     4u   /* CAN 0x014 */
#define RZC_COM_RX_TCU_HEARTBEAT     5u   /* CAN 0x015 */
#define RZC_COM_RX_BCM_HEARTBEAT     6u   /* CAN 0x016 */
#define RZC_COM_RX_VEHICLE_STATE     7u   /* CAN 0x100 */
#define RZC_COM_RX_TORQUE_REQUEST     8u   /* CAN 0x101 */
#define RZC_COM_RX_STEER_COMMAND     9u   /* CAN 0x102 */
#define RZC_COM_RX_BRAKE_COMMAND    10u   /* CAN 0x103 */
#define RZC_COM_RX_STEERING_STATUS    11u   /* CAN 0x200 */
#define RZC_COM_RX_BRAKE_STATUS    12u   /* CAN 0x201 */
#define RZC_COM_RX_BRAKE_FAULT    13u   /* CAN 0x210 */
#define RZC_COM_RX_MOTOR_CUTOFF_REQ    14u   /* CAN 0x211 */
#define RZC_COM_RX_LIDAR_DISTANCE    15u   /* CAN 0x220 */
#define RZC_COM_RX_BODY_CONTROL_CMD    16u   /* CAN 0x350 */
#define RZC_COM_RX_LIGHT_STATUS    17u   /* CAN 0x400 */
#define RZC_COM_RX_INDICATOR_STATE    18u   /* CAN 0x401 */
#define RZC_COM_RX_DOOR_LOCK_STATUS    19u   /* CAN 0x402 */
#define RZC_COM_RX_DTC_BROADCAST    20u   /* CAN 0x500 */
#define RZC_COM_RX_UDS_RESP_TCU    21u   /* CAN 0x644 */
#define RZC_COM_RX_UDS_FUNC_REQUEST    22u   /* CAN 0x7DF */
#define RZC_COM_RX_UDS_PHYS_REQ_CVC    23u   /* CAN 0x7E0 */
#define RZC_COM_RX_UDS_PHYS_REQ_FZC    24u   /* CAN 0x7E1 */
#define RZC_COM_RX_UDS_PHYS_REQ_RZC    25u   /* CAN 0x7E2 */
#define RZC_COM_RX_UDS_PHYS_REQ_TCU    26u   /* CAN 0x7E3 */
#define RZC_COM_RX_UDS_RESP_CVC    27u   /* CAN 0x7E8 */
#define RZC_COM_RX_UDS_RESP_FZC    28u   /* CAN 0x7E9 */

/* ====================================================================
 * Com Signal IDs (index into Com signal config table)
 * Use these instead of hardcoded numbers in Com_SendSignal/Com_ReceiveSignal
 * ==================================================================== */

#define RZC_COM_SIG_RZC_HEARTBEAT_E_2_E_DATA_ID     0u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_RZC_HEARTBEAT_E_2_E_ALIVE_COUNTER     1u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_RZC_HEARTBEAT_E_2_E_CRC_8     2u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_RZC_HEARTBEAT_ECU_ID     3u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_RZC_HEARTBEAT_OPERATING_MODE     4u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_RZC_HEARTBEAT_FAULT_STATUS     5u   /* TX RZC_Heartbeat */
#define RZC_COM_SIG_MOTOR_STATUS_E_2_E_DATA_ID     6u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_E_2_E_ALIVE_COUNTER     7u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_E_2_E_CRC_8     8u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_TORQUE_ECHO     9u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_MOTOR_SPEED_RPM    10u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_MOTOR_DIRECTION    11u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_MOTOR_ENABLE    12u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_STATUS_MOTOR_FAULT_STATUS    13u   /* TX Motor_Status */
#define RZC_COM_SIG_MOTOR_CURRENT_E_2_E_DATA_ID    14u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_E_2_E_ALIVE_COUNTER    15u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_E_2_E_CRC_8    16u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_CURRENT_M_A    17u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_CURRENT_DIRECTION    18u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_MOTOR_ENABLE    19u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_OVERCURRENT_FLAG    20u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_CURRENT_TORQUE_ECHO    21u   /* TX Motor_Current */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_DATA_ID    22u   /* TX Motor_Temperature */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_ALIVE_COUNTER    23u   /* TX Motor_Temperature */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_E_2_E_CRC_8    24u   /* TX Motor_Temperature */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_1_C    25u   /* TX Motor_Temperature */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_WINDING_TEMP_2_C    26u   /* TX Motor_Temperature */
#define RZC_COM_SIG_MOTOR_TEMPERATURE_DERATING_PERCENT    27u   /* TX Motor_Temperature */
#define RZC_COM_SIG_BATTERY_STATUS_E_2_E_DATA_ID    28u   /* TX Battery_Status */
#define RZC_COM_SIG_BATTERY_STATUS_E_2_E_ALIVE_COUNTER    29u   /* TX Battery_Status */
#define RZC_COM_SIG_BATTERY_STATUS_E_2_E_CRC_8    30u   /* TX Battery_Status */
#define RZC_COM_SIG_BATTERY_STATUS_BATTERY_VOLTAGE_M_V    31u   /* TX Battery_Status */
#define RZC_COM_SIG_BATTERY_STATUS_BATTERY_STATUS    32u   /* TX Battery_Status */
#define RZC_COM_SIG_DTC_BROADCAST_DTC_NUMBER    33u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_DTC_BROADCAST_DTC_STATUS    34u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_DTC_BROADCAST_ECU_SOURCE    35u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_DTC_BROADCAST_OCCURRENCE_COUNT    36u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_0    37u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_DTC_BROADCAST_FREEZE_FRAME_1    38u   /* TX DTC_Broadcast */
#define RZC_COM_SIG_UDS_RESP_RZC_UDS_DATA    39u   /* TX UDS_Resp_RZC */
#define RZC_COM_SIG_ESTOP_BROADCAST_E_2_E_DATA_ID    40u   /* RX EStop_Broadcast */
#define RZC_COM_SIG_ESTOP_BROADCAST_E_2_E_ALIVE_COUNTER    41u   /* RX EStop_Broadcast */
#define RZC_COM_SIG_ESTOP_BROADCAST_E_2_E_CRC_8    42u   /* RX EStop_Broadcast */
#define RZC_COM_SIG_ESTOP_BROADCAST_ESTOP_ACTIVE    43u   /* RX EStop_Broadcast */
#define RZC_COM_SIG_ESTOP_BROADCAST_ESTOP_SOURCE    44u   /* RX EStop_Broadcast */
#define RZC_COM_SIG_CVC_HEARTBEAT_E_2_E_DATA_ID    45u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_CVC_HEARTBEAT_E_2_E_ALIVE_COUNTER    46u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_CVC_HEARTBEAT_E_2_E_CRC_8    47u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_CVC_HEARTBEAT_ECU_ID    48u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_CVC_HEARTBEAT_OPERATING_MODE    49u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_CVC_HEARTBEAT_FAULT_STATUS    50u   /* RX CVC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_E_2_E_DATA_ID    51u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_E_2_E_ALIVE_COUNTER    52u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_E_2_E_CRC_8    53u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_ECU_ID    54u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_OPERATING_MODE    55u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_FZC_HEARTBEAT_FAULT_STATUS    56u   /* RX FZC_Heartbeat */
#define RZC_COM_SIG_SC_STATUS_SC_ALIVE_COUNTER    57u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_SC_CRC_8    58u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_SC_MODE    59u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_SC_FAULT_FLAGS    60u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_ECU_HEALTH    61u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_FAULT_REASON    62u   /* RX SC_Status */
#define RZC_COM_SIG_SC_STATUS_RELAY_STATE    63u   /* RX SC_Status */
#define RZC_COM_SIG_ICU_HEARTBEAT_E_2_E_DATA_ID    64u   /* RX ICU_Heartbeat */
#define RZC_COM_SIG_ICU_HEARTBEAT_E_2_E_ALIVE_COUNTER    65u   /* RX ICU_Heartbeat */
#define RZC_COM_SIG_ICU_HEARTBEAT_E_2_E_CRC_8    66u   /* RX ICU_Heartbeat */
#define RZC_COM_SIG_ICU_HEARTBEAT_ALIVE_COUNTER    67u   /* RX ICU_Heartbeat */
#define RZC_COM_SIG_ICU_HEARTBEAT_ECU_ID    68u   /* RX ICU_Heartbeat */
#define RZC_COM_SIG_TCU_HEARTBEAT_E_2_E_DATA_ID    69u   /* RX TCU_Heartbeat */
#define RZC_COM_SIG_TCU_HEARTBEAT_E_2_E_ALIVE_COUNTER    70u   /* RX TCU_Heartbeat */
#define RZC_COM_SIG_TCU_HEARTBEAT_E_2_E_CRC_8    71u   /* RX TCU_Heartbeat */
#define RZC_COM_SIG_TCU_HEARTBEAT_ALIVE_COUNTER    72u   /* RX TCU_Heartbeat */
#define RZC_COM_SIG_TCU_HEARTBEAT_ECU_ID    73u   /* RX TCU_Heartbeat */
#define RZC_COM_SIG_BCM_HEARTBEAT_E_2_E_DATA_ID    74u   /* RX BCM_Heartbeat */
#define RZC_COM_SIG_BCM_HEARTBEAT_E_2_E_ALIVE_COUNTER    75u   /* RX BCM_Heartbeat */
#define RZC_COM_SIG_BCM_HEARTBEAT_E_2_E_CRC_8    76u   /* RX BCM_Heartbeat */
#define RZC_COM_SIG_BCM_HEARTBEAT_ALIVE_COUNTER    77u   /* RX BCM_Heartbeat */
#define RZC_COM_SIG_BCM_HEARTBEAT_ECU_ID    78u   /* RX BCM_Heartbeat */
#define RZC_COM_SIG_VEHICLE_STATE_E_2_E_DATA_ID    79u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_E_2_E_ALIVE_COUNTER    80u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_E_2_E_CRC_8    81u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_VEHICLE_STATE    82u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_FAULT_MASK    83u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_TORQUE_LIMIT    84u   /* RX Vehicle_State */
#define RZC_COM_SIG_VEHICLE_STATE_SPEED_LIMIT    85u   /* RX Vehicle_State */
#define RZC_COM_SIG_TORQUE_REQUEST_E_2_E_DATA_ID    86u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_E_2_E_ALIVE_COUNTER    87u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_E_2_E_CRC_8    88u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_TORQUE_REQUEST    89u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_DIRECTION    90u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_1    91u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_PEDAL_POSITION_2    92u   /* RX Torque_Request */
#define RZC_COM_SIG_TORQUE_REQUEST_PEDAL_FAULT    93u   /* RX Torque_Request */
#define RZC_COM_SIG_STEER_COMMAND_E_2_E_DATA_ID    94u   /* RX Steer_Command */
#define RZC_COM_SIG_STEER_COMMAND_E_2_E_ALIVE_COUNTER    95u   /* RX Steer_Command */
#define RZC_COM_SIG_STEER_COMMAND_E_2_E_CRC_8    96u   /* RX Steer_Command */
#define RZC_COM_SIG_STEER_COMMAND_STEER_ANGLE_CMD    97u   /* RX Steer_Command */
#define RZC_COM_SIG_STEER_COMMAND_STEER_RATE_LIMIT    98u   /* RX Steer_Command */
#define RZC_COM_SIG_STEER_COMMAND_VEHICLE_STATE    99u   /* RX Steer_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_E_2_E_DATA_ID   100u   /* RX Brake_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_E_2_E_ALIVE_COUNTER   101u   /* RX Brake_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_E_2_E_CRC_8   102u   /* RX Brake_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_BRAKE_FORCE_CMD   103u   /* RX Brake_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_BRAKE_MODE   104u   /* RX Brake_Command */
#define RZC_COM_SIG_BRAKE_COMMAND_VEHICLE_STATE   105u   /* RX Brake_Command */
#define RZC_COM_SIG_STEERING_STATUS_E_2_E_DATA_ID   106u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_E_2_E_ALIVE_COUNTER   107u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_E_2_E_CRC_8   108u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_ACTUAL_ANGLE   109u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_COMMANDED_ANGLE   110u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_STEER_FAULT_STATUS   111u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_STEER_MODE   112u   /* RX Steering_Status */
#define RZC_COM_SIG_STEERING_STATUS_SERVO_CURRENT_M_A   113u   /* RX Steering_Status */
#define RZC_COM_SIG_BRAKE_STATUS_E_2_E_DATA_ID   114u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_E_2_E_ALIVE_COUNTER   115u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_E_2_E_CRC_8   116u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_BRAKE_POSITION   117u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_BRAKE_COMMAND_ECHO   118u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_SERVO_CURRENT_M_A   119u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_BRAKE_FAULT_STATUS   120u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_STATUS_BRAKE_MODE   121u   /* RX Brake_Status */
#define RZC_COM_SIG_BRAKE_FAULT_E_2_E_DATA_ID   122u   /* RX Brake_Fault */
#define RZC_COM_SIG_BRAKE_FAULT_E_2_E_ALIVE_COUNTER   123u   /* RX Brake_Fault */
#define RZC_COM_SIG_BRAKE_FAULT_E_2_E_CRC_8   124u   /* RX Brake_Fault */
#define RZC_COM_SIG_BRAKE_FAULT_FAULT_TYPE   125u   /* RX Brake_Fault */
#define RZC_COM_SIG_BRAKE_FAULT_COMMANDED_BRAKE   126u   /* RX Brake_Fault */
#define RZC_COM_SIG_BRAKE_FAULT_MEASURED_BRAKE   127u   /* RX Brake_Fault */
#define RZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_DATA_ID   128u   /* RX Motor_Cutoff_Req */
#define RZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_ALIVE_COUNTER   129u   /* RX Motor_Cutoff_Req */
#define RZC_COM_SIG_MOTOR_CUTOFF_REQ_E_2_E_CRC_8   130u   /* RX Motor_Cutoff_Req */
#define RZC_COM_SIG_MOTOR_CUTOFF_REQ_REQUEST_TYPE   131u   /* RX Motor_Cutoff_Req */
#define RZC_COM_SIG_MOTOR_CUTOFF_REQ_REASON   132u   /* RX Motor_Cutoff_Req */
#define RZC_COM_SIG_LIDAR_DISTANCE_E_2_E_DATA_ID   133u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_E_2_E_ALIVE_COUNTER   134u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_E_2_E_CRC_8   135u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_DISTANCE_CM   136u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_SIGNAL_STRENGTH   137u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_OBSTACLE_ZONE   138u   /* RX Lidar_Distance */
#define RZC_COM_SIG_LIDAR_DISTANCE_SENSOR_STATUS   139u   /* RX Lidar_Distance */
#define RZC_COM_SIG_BODY_CONTROL_CMD_HEADLIGHT_CMD   140u   /* RX Body_Control_Cmd */
#define RZC_COM_SIG_BODY_CONTROL_CMD_TAIL_LIGHT_CMD   141u   /* RX Body_Control_Cmd */
#define RZC_COM_SIG_BODY_CONTROL_CMD_HAZARD_CMD   142u   /* RX Body_Control_Cmd */
#define RZC_COM_SIG_BODY_CONTROL_CMD_TURN_SIGNAL_CMD   143u   /* RX Body_Control_Cmd */
#define RZC_COM_SIG_BODY_CONTROL_CMD_DOOR_LOCK_CMD   144u   /* RX Body_Control_Cmd */
#define RZC_COM_SIG_LIGHT_STATUS_HEADLIGHT_ON   145u   /* RX Light_Status */
#define RZC_COM_SIG_LIGHT_STATUS_TAIL_LIGHT_ON   146u   /* RX Light_Status */
#define RZC_COM_SIG_LIGHT_STATUS_FOG_LIGHT_ON   147u   /* RX Light_Status */
#define RZC_COM_SIG_LIGHT_STATUS_BRAKE_LIGHT_ON   148u   /* RX Light_Status */
#define RZC_COM_SIG_LIGHT_STATUS_HEADLIGHT_LEVEL   149u   /* RX Light_Status */
#define RZC_COM_SIG_INDICATOR_STATE_LEFT_INDICATOR   150u   /* RX Indicator_State */
#define RZC_COM_SIG_INDICATOR_STATE_RIGHT_INDICATOR   151u   /* RX Indicator_State */
#define RZC_COM_SIG_INDICATOR_STATE_HAZARD_ACTIVE   152u   /* RX Indicator_State */
#define RZC_COM_SIG_INDICATOR_STATE_BLINK_STATE   153u   /* RX Indicator_State */
#define RZC_COM_SIG_DOOR_LOCK_STATUS_FRONT_LEFT_LOCK   154u   /* RX Door_Lock_Status */
#define RZC_COM_SIG_DOOR_LOCK_STATUS_FRONT_RIGHT_LOCK   155u   /* RX Door_Lock_Status */
#define RZC_COM_SIG_DOOR_LOCK_STATUS_REAR_LEFT_LOCK   156u   /* RX Door_Lock_Status */
#define RZC_COM_SIG_DOOR_LOCK_STATUS_REAR_RIGHT_LOCK   157u   /* RX Door_Lock_Status */
#define RZC_COM_SIG_DOOR_LOCK_STATUS_CENTRAL_LOCK   158u   /* RX Door_Lock_Status */
#define RZC_COM_SIG_UDS_RESP_TCU_UDS_DATA   159u   /* RX UDS_Resp_TCU */
#define RZC_COM_SIG_UDS_FUNC_REQUEST_UDS_DATA   160u   /* RX UDS_Func_Request */
#define RZC_COM_SIG_UDS_PHYS_REQ_CVC_UDS_DATA   161u   /* RX UDS_Phys_Req_CVC */
#define RZC_COM_SIG_UDS_PHYS_REQ_FZC_UDS_DATA   162u   /* RX UDS_Phys_Req_FZC */
#define RZC_COM_SIG_UDS_PHYS_REQ_RZC_UDS_DATA   163u   /* RX UDS_Phys_Req_RZC */
#define RZC_COM_SIG_UDS_PHYS_REQ_TCU_UDS_DATA   164u   /* RX UDS_Phys_Req_TCU */
#define RZC_COM_SIG_UDS_RESP_CVC_UDS_DATA   165u   /* RX UDS_Resp_CVC */
#define RZC_COM_SIG_UDS_RESP_FZC_UDS_DATA   166u   /* RX UDS_Resp_FZC */
#define RZC_COM_SIG_COUNT   167u

/* ====================================================================
 * DTC Event IDs (Dem_EventIdType)
 * ==================================================================== */

#define RZC_DTC_OVERCURRENT     0u
#define RZC_DTC_OVERTEMP     1u
#define RZC_DTC_STALL     2u
#define RZC_DTC_DIRECTION     3u
#define RZC_DTC_SHOOT_THROUGH     4u
#define RZC_DTC_CAN_BUS_OFF     5u
#define RZC_DTC_CMD_TIMEOUT     6u
#define RZC_DTC_SELF_TEST_FAIL     7u
#define RZC_DTC_WATCHDOG_FAIL     8u
#define RZC_DTC_BATTERY     9u
#define RZC_DTC_ENCODER    10u
#define RZC_DTC_ZERO_CAL    11u

/* ====================================================================
 * E2E Data IDs
 * ==================================================================== */

#define RZC_E2E_HEARTBEAT_DATA_ID  0x04u
#define RZC_E2E_MOTOR_STATUS_DATA_ID  0x0Eu
#define RZC_E2E_MOTOR_CURRENT_DATA_ID  0x0Fu
#define RZC_E2E_MOTOR_TEMP_DATA_ID  0x10u
#define RZC_E2E_BATTERY_DATA_ID  0x11u
#define RZC_E2E_ESTOP_DATA_ID  0x01u
#define RZC_E2E_VEHSTATE_DATA_ID  0x05u

/* ====================================================================
 * Enums
 * ==================================================================== */

#define RZC_STATE_INIT     0u
#define RZC_STATE_RUN     1u
#define RZC_STATE_DEGRADED     2u
#define RZC_STATE_LIMP     3u
#define RZC_STATE_SAFE_STOP     4u
#define RZC_STATE_SHUTDOWN     5u
#define RZC_STATE_COUNT     6u

/* ====================================================================
 * Thresholds
 * ==================================================================== */

#define RZC_RTE_PERIOD_MS    50u
#define RZC_COMM_TIMEOUT   100u
#define RZC_MOTOR_OVERCURRENT_LIMIT  4000u
#define RZC_MOTOR_OVERSPEED_LIMIT  6000u
#define RZC_MOTOR_OVERTEMP_LIMIT   850u
#define RZC_BATTERY_LOW_MV  2200u
#define RZC_BATTERY_CRITICAL_MV  2000u
#define RZC_ENCODER_TIMEOUT    50u

/* ====================================================================
 * Application-specific constants (hand-authored, not generated)
 * ==================================================================== */
#if __has_include("Rzc_App.h")
#include "Rzc_App.h"
#endif

#endif /* RZC_CFG_H */
